const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = __dirname;
const page = fs.readFileSync(path.join(root, "name-randomiser.html"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");

[
  "Name Randomiser",
  "Randomly select students to perform, participate in activities or answer questions.",
  "names-icon.svg",
  "name-randomiser-core.js",
  "window.MLH.AppHeader",
  "window.MLH.CustomiseButton",
  "Sound Effects",
  "spin.mp3",
  "playFeedbackSound?.(true, true, \"bronze\")",
  "Add Name",
  ">Add</button>",
  "Saved Lists",
  "Save Current List",
  "Remove Name",
  "localStorage",
  "role=\"dialog\"",
  "aria-live=\"polite\"",
  "prefers-reduced-motion: reduce",
  "footer.js",
].forEach((required) => assert(page.includes(required), `Missing Name Randomiser safeguard: ${required}`));

assert(page.includes("nextSegments.length < 2"), "The wheel must require two names before spinning");
assert(page.includes("const chosenIndex = CORE.chooseIndex(nextSegments.length)"), "The winner must be chosen fairly before the visual landing position is calculated");
assert(page.includes('className="names-winner-panel"') && page.includes('.names-winner-panel { position: absolute; z-index: 6; top: 50%; left: 50%; width: min(420px, calc(100% - 40px)); transform: translate(-50%, -50%);') && page.includes('className={`names-wheel-stage ${wheelOverlayOpen ? "has-wheel-overlay" : ""}`}') && page.includes('.names-wheel-stage.has-wheel-overlay .names-wheel, .names-wheel-stage.has-wheel-overlay .names-slots-window, .names-wheel-stage.has-wheel-overlay .names-wheel-pointer, .names-wheel-stage.has-wheel-overlay .names-spin-button { opacity: .24; filter: grayscale(1); }') && !page.includes('{winner && <Dialog title="Selected"'), "In-wheel decision panels should sit over the active randomiser while its background and controls are dimmed");
assert(page.indexOf('onClick={removeSelectedName}>Remove Name</button>') < page.indexOf('onClick={() => setWinner(null)}>Continue</button>') && page.includes('.names-winner-panel .names-dialog-actions { flex-direction: row; flex-wrap: nowrap;'), "Selected-name actions should share one row with Remove Name on the left and Continue on the right");
assert(page.includes('.names-winner-panel:not(.names-wheel-confirm-panel) .names-winner { transform: translateY(11px); }') && page.includes('.names-winner-panel:not(.names-wheel-confirm-panel) .names-dialog-actions { margin-top: 42px; border-top: 1px solid #d6d3d1; padding-top: 23px; }'), "The selected name should be visually centred between the panel top and a divider positioned 10px lower above its action buttons");
assert(page.includes('setPendingRemoval(selected);') && page.includes('Remove {pendingRemoval.names.join(" and ")}?') && page.includes('onClick={confirmRemoveSegment}>Confirm</button>') && page.includes('onClick={() => setPendingRemoval(null)}>Cancel</button>'), "Clicking a name should request confirmation inside the wheel before removal");
assert(page.includes('function removeSelectedName()') && page.includes('onClick={removeSelectedName}>Remove Name</button>') && !page.includes('function removeAndSpinAgain()'), "Remove Name should remove the selected entry without automatically spinning again");
assert(page.includes("segment.names.flatMap") && page.includes("wrapName(name, maxChars)"), "Each name should wrap inside its wheel segment");
assert(page.includes("Math.min(28, 34 - count * 1.05)") && page.includes("190 / (longestLine * .62)"), "Names should start substantially larger and shrink dynamically for narrower segments or longer text");
assert(page.includes('const segmentFill = index % 2 === 0 ? "#fff" : alternateColour;') && page.includes('const segmentTextColour = segmentFill === "#111111" ? "#fff" : "#111";') && page.includes('fill={segmentTextColour}'), "Wheel segments should alternate between white and the selected colour, using white text on black segments");
assert(page.includes('CORE.SEGMENT_COLOURS.map') && page.includes('Accent Colour') && page.includes('setSegmentColour(colour.value)') && page.includes('segmentColour, randomiserMethod }));'), "Customise should offer and remember accessible accent colours for the alternating Wheel and Slots entries");
assert(page.includes('audio: "audio-svgrepo-com.svg?v=20260722-smaller15"') && page.includes('scale-[1.5] object-contain'), "Sound Effects should use the shared reduced audio glyph treatment");
assert(page.includes('.names-layout { display: flex; width: 100%; min-height: 0; flex: 1; }') && !page.includes("function CurrentSegments"), "The wheel panel should use the full content width without a left column");
assert(page.includes('className="names-wheel-empty"><span className="names-empty-title">Welcome!</span><span className="names-empty-description">Add a name to get started.</span></div>') && page.includes('animation: namesWelcomeSpin 4s ease-in-out infinite;') && page.includes('@keyframes namesWelcomeSpin { 0% { transform: rotate(0); } 12% { transform: rotate(360deg); } 100% { transform: rotate(360deg); } }') && page.includes('.names-wheel-empty { animation: none !important; }'), "The empty-wheel message should stay upright between quick four-second spins and respect reduced-motion settings");
assert(page.includes('const landingFraction = .04 + Math.random() * .92;') && page.includes('const target = 180 - (chosenIndex * slice + slice * landingFraction);') && page.includes('M7 5 L7 53 L62 29 Z') && page.includes('.names-wheel-pointer-group { position: absolute; z-index: 5; left: -6px; top: 50%; display: flex; align-items: center; gap: 10px; transform: translate(-120px, -50%); }') && page.includes('.names-wheel-pointer { display: block; width: 68px; height: 58px;'), "The pointer should land at a random safe position within the fairly selected segment, sit 3px farther left and remain aligned with the wheel's centre dot");
assert(page.includes('--names-shared-shadow: 0 12px 20px rgba(28,25,23,.12)') && page.includes('.names-wheel { width: 100%; height: 100%; overflow: visible; filter: drop-shadow(var(--names-shared-shadow)); }') && page.includes('.names-wheel-pointer { display: block; width: 68px; height: 58px; flex: none; filter: drop-shadow(var(--names-shared-shadow)); }') && page.includes('.names-primary-button.names-spin-button { box-shadow: var(--names-shared-shadow); }'), "The wheel, pointer and Spin button should use the same shadow specification");
assert(page.includes('style={{ fontSize: `${baseFontSize}px`, fontWeight: 800 }}'), "Spin should use the same dynamic font size and weight as the wheel names");
assert(page.includes('disabled={spinDisabled} onClick={onSpin}>Spin</button>') && !page.includes("SPINNING…"), "The Spin button should keep the same title-cased label throughout its animation");
assert(!page.includes('namesSpinPulse') && !page.includes('.names-spin-button:not(:disabled) { animation:'), "The Spin button should not use a recurring bounce animation");
assert(!page.includes('.names-spin-button:disabled { visibility: hidden; }') && page.includes('.names-primary-button:disabled, .names-secondary-button:disabled, .names-danger-button:disabled { cursor: not-allowed; opacity: .42;'), "The Spin button should remain visible in its standard grey disabled state while inactive");
assert(page.includes('if (randomiserMethod === "Slots" && segments.length) setSlotPosition((current) => current + .004);') && page.includes('else if (randomiserMethod === "Wheel") setRotation((current) => current + .3);') && page.includes('if (spinning || winner || pendingRemoval || reducedMotion) return undefined;') && page.includes('const wheelLocked = spinning || wheelOverlayOpen;') && page.includes('const removable = !segment.preview && !locked;'), "Wheel and Slots should each idle slowly but fully freeze while an in-app decision awaits confirmation");
assert(page.includes('CORE.RANDOMISER_METHODS.map') && page.includes('<span>{randomiserMethod}</span>') && page.includes('setRandomiserMethod(method)') && page.includes('segmentColour, randomiserMethod }));'), "The toolbar should offer and remember the current Wheel or Slots method immediately after Customise");
assert(!page.includes('names-method-chevron') && !page.includes('aria-hidden="true">▼'), "The method button should not display a drop-down arrow");
assert(page.includes('src={randomiserMethod === "Wheel" ? ASSET.wheel : ASSET.slots}') && page.includes('className="names-method-button-glyph"') && page.includes('.names-method-button-glyph { display: block; width: 26px; height: 26px;'), "The method toolbar button should show the selected Wheel or Slots glyph to the left of its label");
assert(page.includes('className="hub-menu-anchor names-method-anchor relative"') && page.includes('.names-method-anchor > .hub-menu-panel-level { width: min(300px, calc(100vw - 48px)); max-width: 300px; }'), "The Method menu should use a compact width with the Hub's standard panel padding");
assert(page.includes('const textRadius = count === 1 ? 140 :') && page.includes('.names-wheel-segment:focus { outline: none; }'), "A single name should sit clear of the centre dot without showing an oversized SVG focus outline");
assert(page.includes('const segmentSymbol = MUSIC_BORDER_GLYPHS[index % MUSIC_BORDER_GLYPHS.length];') && page.includes('className="names-wheel-segment-symbol"') && page.includes('dx={Math.max(5, fontSize * .25)}') && page.includes('{segmentSymbol}</tspan>') && !page.includes('function MusicNoteBorder') && !page.includes('names-wheel-crotchet'), "Each Wheel segment should show one Bravura symbol immediately to the right of its name, with no outer symbol border or dangling physics");
assert(page.includes('label="Symbols"') && page.includes('checked={borderSymbols}') && page.includes('setBorderSymbols((visible) => !visible)') && page.includes('{showBorder && textLines.length > 0 && <tspan className="names-wheel-segment-symbol"') && page.includes('soundEffects, borderSymbols, segmentColour, randomiserMethod }));'), "Customise should label the control Symbols, hide or show the decorative Bravura symbols and remember the preference");
assert(page.includes('.names-border-toggle-glyph { display: inline-flex; width: 28px; height: 22px;') && page.includes('.names-border-toggle-glyph > span { font-family: "Bravura", serif; font-size: 20px;') && page.includes('transform: translateY(4px);') && page.includes('<span className="names-border-toggle-glyph" aria-hidden="true"><span>{"\\uE050"}</span></span>'), "The Symbols glyph should use the same sizing and optical alignment as Millionaire's Music Literacy glyph");
assert(page.includes('const rowSymbol = MUSIC_BORDER_GLYPHS[segmentIndex % MUSIC_BORDER_GLYPHS.length];') && page.includes('className="names-slots-row-content"') && page.includes('className={`names-slots-row-symbol ${showBorder ? "" : "is-hidden"}`}') && page.includes('.names-slots-row-symbol.is-hidden { visibility: hidden; }') && !page.includes('<MusicNoteBorder shape="square" />'), "Each Slots name should scroll with the same Bravura symbol attached on both sides instead of using an outer symbol border");
assert(page.includes('.names-slots-row-content { display: grid; width: 100%; height: 100%;') && page.includes('.names-slots-row-symbol { display: inline-flex; width: 42px; height: 100%; align-items: center; justify-content: center; justify-self: center;') && page.includes('text-decoration: none; transform: translateY(4px);') && page.includes('.names-slots-row.is-removable:hover .names-slots-row-name, .names-slots-row.is-removable:focus-visible .names-slots-row-name { text-decoration: line-through;'), "Slots symbols should remain vertically centred in their side columns while strike-through applies only to the name");
assert(page.includes('wheel: "wheel2.svg"') && page.includes('slots: "slots.svg"') && page.includes('className="names-method-badge"') && page.includes('src={method === "Wheel" ? ASSET.wheel : ASSET.slots}') && page.includes('className="names-method-label"') && page.includes('{active && <img src={ASSET.tick}') && !page.includes('randomiserMethod === method ? "✓"'), "Method choices should match the Level menu card pattern, use wheel2.svg and slots.svg, and show tick.svg for the active method");
assert(page.includes('.names-method-option { width: 100%; border: 1px solid #d6d3d1; border-radius: 12px; background: #f5f5f4;') && page.includes('.names-method-option[aria-pressed="true"] { border-color: #a8a29e; background: #e7e5e4; }') && page.includes('.names-method-badge { display: flex;') && page.includes('background: white;'), "Method choices should place their white glyph containers inside visibly grey option cards");
assert(page.includes('.names-page .hub-toolbar .names-method-option { height: auto !important; min-height: 64px !important; }') && page.includes('.names-method-option-inner { display: flex; min-height: 46px;') && page.includes('padding: 8px 12px;'), "Grey method cards should override the toolbar's 44px control height and fit each 46px white glyph container with default vertical padding");
assert(page.includes('save: "save.svg"') && page.includes('src={ASSET.save}') && page.includes('className="names-toolbar-save-glyph"') && page.includes('.names-toolbar-save-glyph { display: block; width: 21px; height: 21px;') && !page.includes('names-toolbar-chevron'), "The direct Save button should show a compact save.svg to the left of its label without a chevron");
assert(page.includes('function SlotMachine(') && page.includes('Array.from({ length: 7 }') && page.includes('rowIndex - 3') && page.includes('names-slots-window::before') && page.includes('names-slots-window::after') && page.includes('linear-gradient(to bottom') && page.includes('linear-gradient(to top'), "Slots should display five useful scrolling rows with soft white fades above and below");
assert(page.includes('.names-wheel-wrap { position: relative; width: auto; height: min(calc(100% - 24px), 850px); max-width: 100%; aspect-ratio: 1; margin: 0 auto; }') && page.includes('.names-slots-wrap { position: relative; width: auto; height: min(calc(100% - 24px), 850px); max-width: 100%; aspect-ratio: 1; margin: 0 auto; }'), "Wheel and Slots should use identical outer frames so the Spin button and pointer do not move between methods");
assert(page.includes('const MIN_SPIN_DURATION = 6000;') && page.includes('cubic-bezier(.08,.68,.12,1)') && page.includes('function animateSlots(start, target, duration)') && page.includes('1 - Math.pow(1 - progress, 4)') && page.includes('nextSegments.length * 6 + slotDelta') && page.includes('setSlotPosition(nextSegments.length * 2 + chosenIndex)'), "Wheel and Slots should decelerate gradually before stopping with the fairly chosen name beside the pointer");
assert(page.includes('const rowColour = segmentIndex % 2 === 0 ? "#fff" : alternateColour;') && page.includes('color: rowColour === "#111111" ? "#fff" : "#111"') && page.includes('fontSize = Math.max(17, 36 - distance * 7)'), "Slot rows should alternate white and the selected colour, use white text on black, and enlarge the name nearest the pointer");
assert(page.includes(">Saved lists will appear here</p>"), "The empty saved-list message should explain where saved lists will appear");
assert(page.includes('names-main !min-h-[740px]') && page.includes('.names-main { display: flex; flex-direction: column; }') && page.includes('min-height: 610px; flex: 1;') && page.includes('height: min(calc(100% - 24px), 850px);') && !page.includes("wheelPanelHeight") && !page.includes("matchWheelHeight") && !page.includes("ResizeObserver"), "The wheel panel should fill the main container to its default padding through a stable flex layout");
const wheelStageRule = page.match(/\.names-wheel-stage \{([^}]*)\}/)?.[1] || "";
assert(wheelStageRule.includes("position: relative") && !/border(?!-box)|background|box-shadow|border-radius/.test(wheelStageRule), "The wheel stage should retain its layout without a grey nested panel, border or shadow");
assert(!page.includes('r="42"') && page.includes('{count > 0 && <circle cx="300" cy="300" r="10" fill="#111" />}'), "The single black centre dot should appear only when the wheel contains a name");
assert(page.includes('.names-page > header > div { max-width: 1500px; }') && page.includes('names-page`}>'), "The Name Randomiser header should share the wider main-container alignment");
assert(!page.includes("names-spin-note"), "The add-name instruction should not be repeated beneath the wheel");
assert(page.includes('const displayedSegments = previewName ? [...segments, { id: "draft-preview"') && page.includes('<Wheel segments={displayedSegments}'), "Typing should display a live preview segment before Add is pressed");
assert(page.includes('setDraftName(CORE.capitaliseNameInput(event.target.value))') && page.includes('autoCapitalize="words"'), "The name field should capitalise the first letter of every entered word");
assert(page.includes('.names-toolbar-name { font-size: 14px; font-weight: 400; }') && page.includes('.names-primary-button.names-toolbar-add { font-size: 14px; font-weight: 600; }'), "The Name field should use regular-weight text while Add retains the Customise control's semibold typography");
assert(page.includes('.names-page .hub-toolbar button, .names-page .hub-toolbar input { height: 44px !important; min-height: 44px !important; box-sizing: border-box; }'), "Customise, Name, Add, Save and Clear should share an exact 44px toolbar height");
assert(page.includes('.names-add-group { position: absolute; left: 50%; display: flex; align-items: center; gap: 8px; transform: translateX(-130px); }') && page.includes('className="names-add-group" role="group" aria-label="Add Name"'), "The centre of the 260px Name field should align exactly with the centre of the main toolbar container");
assert(page.includes('segments.length < 2 || Boolean(previewName)'), "Spin should remain unavailable until the live preview is committed with Add");
assert(page.includes('className={`names-wheel-segment ${segment.preview ? "is-preview" : ""} ${removable ? "is-removable"') && page.includes('.names-wheel-segment.is-removable:hover .names-segment-label { text-decoration: line-through;') && page.includes('if (event.pointerType === "touch")') && page.includes('if (armedRemoveId === segment.id)') && page.includes('role={!segment.preview ? "button" : undefined}') && page.includes('event.key === "Enter" || event.key === " "') && page.includes('<text className="names-segment-label"') && !page.includes("names-remove-control"), "Each complete segment should provide hover strike-through, two-tap touch removal and accessible keyboard removal");
assert(page.includes('className={`${window.MLH.ToolbarButtonClass} names-toolbar-clear sm:min-w-[92px]`}') && page.includes('>Clear</button>') && page.includes('.names-toolbar-clear { border-color: #dc2626 !important; background: #dc2626 !important; color: #fff !important; }') && !page.includes("names-wheel-clear") && !page.includes("Current wheel"), "Clear should use a red fill with white text and the same explicit width as Save");
assert(page.includes('@media (min-width: 640px) { .names-toolbar-save, .names-toolbar-clear { width: 92px; } }'), "Save and Clear should have matching desktop widths");
assert(page.includes('right={<div className="flex items-center gap-2">') && page.includes('ref={savedListsRef}') && page.includes('>Saved Lists</button>') && page.includes('<window.MLH.MenuPanel title="Saved Lists" position="right-0"') && page.includes('names-toolbar-save gap-2 sm:min-w-[92px]') && page.includes('disabled={wheelLocked || !segments.length} onClick={() => { setCustomiseOpen(false); setMethodOpen(false); setSavedListsOpen(false); requestSave(); }}') && page.includes('<span>Save</span>') && page.includes('.names-toolbar-save { border-color: #000 !important; background: #000 !important; color: #fff !important; }') && page.indexOf('>Saved Lists</button>') < page.indexOf('<span>Save</span>') && page.indexOf('<span>Save</span>') < page.indexOf('>Clear</button>') && !page.includes('<section className="names-panel mt-3" aria-labelledby="saved-lists-title">'), "Saved Lists should have its own dropdown to the left of a direct black Save button and Clear");
assert(page.includes('const textRadius = count === 1 ? 140 : (4 * 260 * Math.sin(sliceRadians / 2)) / (3 * sliceRadians);') && page.includes('x={textX} y="300" transform={`rotate(180 ${textX} 300)`}'), "Every flipped name label should use the visual centre of its dynamically sized segment, with a single name kept clear of the centre dot");
assert(page.includes('.names-toolbar-name { width: 260px; }') && page.includes('.names-toolbar-add { width: 92px; min-width: 92px; }') && page.includes('.names-spin-button { min-width: 110px; min-height: 58px; height: 58px;') && page.includes('feedback={<NameComposer draftName={draftName} setDraftName={setDraftName} addName={addName} disabled={wheelLocked} />}') && page.includes('<div className="names-wheel-pointer-group">\n      <button type="button" className="names-primary-button names-spin-button"') && page.includes('onSpin={() => performSpin()} spinDisabled={wheelLocked || segments.length < 2 || Boolean(previewName)}'), "The wider Add Name controls should use the centre toolbar section while Add matches Save's width and Spin matches the pointer's height");
assert(page.includes('<circle cx="300" cy="300" r="260" fill="#fff" stroke="#111" strokeWidth="1.25" />') && page.includes('strokeWidth={count > 35 ? .75 : 1.25}'), "The wheel outline and segment boundaries should remain visible without appearing heavy");
assert(page.includes('.names-empty-title { color: #111; font-size: 28px; font-weight: 800;') && page.includes('.names-empty-description { margin-top: 4px; color: #a8a29e; font-size: 14px; font-weight: 400;') && page.includes('<span className="names-empty-title">Welcome!</span><span className="names-empty-description">Add a name to get started.</span>'), "The empty-state welcome should match Spin text sizing while its instruction matches the Name field placeholder");
assert(!page.includes(">+ Add another name</button>") && !page.includes(">Add to wheel</button>") && !page.includes("Add another box to put a pair or group"), "The Add Name panel should use the approved simplified controls");
assert(page.includes("Loading") && page.includes("will replace the current wheel"), "Loading a saved list should warn before replacing the wheel");
assert(page.includes("Saved lists will not be affected"), "Clearing the current wheel must not delete saved lists");

assert(index.includes('"Name Randomiser": "names-icon.svg"'), "The Hub should map the supplied Name Randomiser icon");
assert(index.includes('href: "name-randomiser.html", title: "Name Randomiser"'), "The Name Randomiser should appear in the Hub app data");
assert(index.includes('audio: true, disabled: [], direct: true'), "The Name Randomiser card should open directly without qualification levels");
assert(index.includes('data-direct="${app.direct === true}"') && index.includes('if (card.dataset.direct === "true")'), "Direct Hub cards should bypass the level picker while retaining the normal card layout");
assert(index.includes('<span class="arrow"><svg'), "Direct Hub cards should retain the shared chevron");
assert(index.indexOf('{ category: "Other"') < index.indexOf('href: "name-randomiser.html"'), "The Name Randomiser should be listed under Other");

console.log("Name Randomiser integration tests passed.");
