const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const root = __dirname;
const page = fs.readFileSync(path.join(root, "name-randomiser.html"), "utf8");
const coreSource = fs.readFileSync(path.join(root, "name-randomiser-core.js"), "utf8");
const index = fs.readFileSync(path.join(root, "index.html"), "utf8");
const shell = fs.readFileSync(path.join(root, "hub-shell.js"), "utf8");

[
  "Name Randomiser",
  "Randomly select students to perform, participate in activities or answer questions.",
  "names-icon.svg",
  "name-randomiser-core.js",
  "window.MLH.AppHeader",
  "window.MLH.CustomiseButton",
  "Sound Effects",
  "spin.mp3",
  "playFeedbackSound?.(true, true, \"bronze\")",
  "Add Name",
  ">Add</button>",
  "Saved Classes",
  "Save Class",
  "Save the names currently in the randomiser to a class set you can use.",
  "Remove Name",
  "localStorage",
  "role=\"dialog\"",
  "aria-live=\"polite\"",
  "prefers-reduced-motion: reduce",
  "footer.js",
].forEach((required) => assert(page.includes(required), `Missing Name Randomiser safeguard: ${required}`));

assert(page.includes("nextSegments.length < 2"), "The wheel must require two names before spinning");
assert(page.includes("const chosenIndex = CORE.chooseIndex(nextSegments.length)"), "The winner must be chosen fairly before the visual landing position is calculated");
assert(page.includes('ref={winnerPanelRef} className="names-winner-panel" role="dialog"') && page.includes('.names-winner-panel { position: absolute; z-index: 6; top: 50%; left: 50%; width: min(420px, calc(100% - 40px)); transform: translate(-50%, -50%);') && page.includes('className={`names-wheel-stage ${randomiserMethod === "Rows" ? "is-rows" : "is-wheel"} ${wheelOverlayOpen ? "has-wheel-overlay" : ""}`}') && page.includes('.names-wheel-stage.has-wheel-overlay .names-wheel, .names-wheel-stage.has-wheel-overlay .names-slots-window, .names-wheel-stage.has-wheel-overlay .names-wheel-pointer, .names-wheel-stage.has-wheel-overlay .names-spin-button { opacity: .24; }') && !page.includes('opacity: .24; filter: grayscale(1);') && page.includes('.names-wheel-stage.has-wheel-overlay .names-spin-button { box-shadow: none; }') && !page.includes('{winner && <Dialog title="Selected"'), "In-wheel decision panels should sit over the active randomiser while its colours remain visible beneath the dimmed overlay");
assert(page.indexOf('onClick={removeSelectedName}>Remove Name</button>') < page.indexOf('onClick={() => setWinner(null)}>Continue</button>') && page.includes('.names-winner-panel .names-dialog-actions { flex-direction: row; flex-wrap: nowrap;'), "Selected-name actions should share one row with Remove Name on the left and Continue on the right");
assert(page.includes('.names-winner-panel:not(.names-wheel-confirm-panel) .names-winner { transform: translateY(22px); }') && page.includes('.names-winner-panel:not(.names-wheel-confirm-panel) .names-dialog-actions { margin-top: 66px; }') && !page.includes('.names-winner-panel:not(.names-wheel-confirm-panel) .names-dialog-actions { margin-top: 42px; border-top:'), "The selected name should sit midway between the panel top and its action buttons without a divider line");
assert(page.includes('.names-winner span { display: block; transform-origin: center; animation: namesWinnerPulse .9s ease-in-out infinite; }') && page.includes('@keyframes namesWinnerPulse { 0%, 100% { transform: scale(1); } 50% { transform: scale(1.14); } }') && page.includes('.names-winner span { animation: none !important; }'), "The selected name should pulse strongly and continuously while respecting reduced-motion preferences");
assert(page.includes('setPendingRemoval(selected);') && page.includes('Remove {pendingRemoval.names.join(" and ")}?') && page.includes('onClick={confirmRemoveSegment}>Confirm</button>') && page.includes('onClick={() => setPendingRemoval(null)}>Cancel</button>'), "Clicking a name should request confirmation inside the wheel before removal");
assert(page.includes('winnerPanelRef.current?.querySelector("button")?.focus()') && page.includes('removalPanelRef.current?.querySelector("button")?.focus()') && page.includes('ref={removalPanelRef} className="names-winner-panel names-wheel-confirm-panel" role="dialog"'), "Winner and removal decisions should identify themselves as dialogs and move keyboard focus into their actions");
assert(page.includes('function removeSelectedName()') && page.includes('onClick={removeSelectedName}>Remove Name</button>') && !page.includes('function removeAndSpinAgain()'), "Remove Name should remove the selected entry without automatically spinning again");
assert(page.includes("segment.names.flatMap") && page.includes("wrapName(name, maxChars)"), "Each name should wrap inside its wheel segment");
assert(page.includes("function randomiserFontSize(count)") && page.includes("Math.min(28, 34 - count * 1.05)") && page.includes("190 / (longestLine * .62)"), "Names should start substantially larger and shrink dynamically for narrower segments or longer text");
assert(page.includes('const colourPalette = CORE.segmentColourPalette(selectedColour);') && page.includes('const segmentFill = colourPalette[index % colourPalette.length];') && page.includes('fill={textColour}') && page.includes('fill === "#111111" ? "#fff" : "#111"') && !page.includes('alternateColour'), "Wheel segments should cycle through the selected colour palette and use white text on black");
assert(page.includes('CORE.SEGMENT_COLOURS.map') && page.includes('<window.MLH.MenuSubheading>Colour</window.MLH.MenuSubheading>') && page.includes('setSegmentColour(colour.value)') && page.includes('segmentColour, randomiserMethod }));'), "Customise should offer and remember accessible colours for the alternating Wheel and Slots entries");
assert(coreSource.includes('{ id: "multi", label: "Multi", value: MULTI_SEGMENT_COLOUR, palette: MULTI_SEGMENT_PALETTE }') && coreSource.indexOf('{ id: "multi"') < coreSource.indexOf('{ id: "white"') && coreSource.includes('{ id: "white", label: "White", value: WHITE_SEGMENT_COLOUR, strongValue: "#fafaf9" }'), "Multi should be first and White should retain the shared Sound Effects control grey");
assert(page.includes('.names-colour-grid { box-sizing: border-box; display: grid; width: 100%; grid-template-columns: repeat(4, 34px); justify-content: space-between; column-gap: 0; row-gap: 12px; padding: 0 14px; }'), "Colour swatches should spread across the same padded content width as the Sound Effects control");
assert(page.includes('audio: "audio-svgrepo-com.svg?v=20260722-smaller15"') && page.includes('scale-[1.5] object-contain'), "Sound Effects should use the shared reduced audio glyph treatment");
assert(page.includes('.names-layout { display: flex; width: 100%; min-height: 0; flex: 1; }') && !page.includes("function CurrentSegments"), "The wheel panel should use the full content width without a left column");
assert(page.includes('className="names-wheel-empty"><span className="names-empty-title">Welcome!</span><span className="names-empty-description">Add a name to get started.</span></div>') && page.includes('animation: namesWelcomeSpin 4s ease-in-out infinite;') && page.includes('@keyframes namesWelcomeSpin { 0% { transform: rotate(0); } 12% { transform: rotate(360deg); } 100% { transform: rotate(360deg); } }') && page.includes('.names-wheel-empty { animation: none !important; }'), "The empty-wheel message should stay upright between quick four-second spins and respect reduced-motion settings");
assert(page.includes('const landingFraction = .04 + Math.random() * .92;') && page.includes('const target = 180 - (chosenIndex * slice + slice * landingFraction);') && page.includes('M5 13 L5 45 Q5 57 15.94 52.06 L56.06 33.94 Q67 29 56.06 24.06 L15.94 5.94 Q5 1 5 13 Z') && page.includes('.names-wheel-pointer-group { position: absolute; z-index: 5; left: 0; top: 50%; display: flex; align-items: center; gap: 10px; transform: translate(-120px, -50%); }') && page.includes('.names-wheel-pointer { display: block; width: 73px; height: 62px;'), "The pointer should retain the Spin button's curvature and proportional frame while the complete control group uses its approved 5px rightward position");
assert(page.includes('function spinArrowOutline(selectedColour, spinColour)') && page.includes('if (selectedColour === "#111111") return "#fff";') && page.includes('return spinColour === "#111111" ? "none" : "#111";') && (page.match(/stroke=\{arrowOutline\}/g) || []).length === 2 && (page.match(/strokeWidth=\{arrowOutline === "none" \? 0 : 1\}/g) || []).length === 2, "Wheel and Rows arrows should match the Spin button's 1px outline, retain Black's white outline and leave White plain");
assert((page.match(/const spinColour = CORE\.spinControlColour\(selectedColour\);/g) || []).length === 2 && (page.match(/const spinButtonColour = spinColour;/g) || []).length === 2 && (page.match(/fill=\{spinColour\}/g) || []).length === 2 && (page.match(/backgroundColor: spinButtonColour, borderColor: "#111", color: segmentTextColour\(spinButtonColour\)/g) || []).length === 2, "Wheel and Rows should use matching outlined Spin button and arrow fills, including white controls with black text for Multi");
assert(page.includes('--names-shared-shadow: 0 12px 20px rgba(28,25,23,.12)') && page.includes('.names-wheel { width: 100%; height: 100%; overflow: visible; filter: drop-shadow(var(--names-shared-shadow)); }') && page.includes('.names-wheel-pointer { display: block; width: 73px; height: 62px; flex: none; filter: drop-shadow(var(--names-shared-shadow)); }') && page.includes('.names-primary-button.names-spin-button { box-shadow: var(--names-shared-shadow); }'), "The wheel, pointer and Spin button should use the same shadow specification");
assert(page.includes('fontSize: `${baseFontSize}px`, fontWeight: 800') && page.includes('const spinFontSize = randomiserFontSize(count);') && page.includes('fontSize: `${spinFontSize}px`, fontWeight: 800'), "Wheel and Rows Spin labels should use the same dynamic font size and weight");
assert(page.includes('disabled={spinDisabled} onClick={onSpin}>Spin</button>') && !page.includes("SPINNING…"), "The Spin button should keep the same title-cased label throughout its animation");
assert(!page.includes('namesSpinPulse') && !page.includes('.names-spin-button:not(:disabled) { animation:'), "The Spin button should not use a recurring bounce animation");
assert(page.includes('.names-primary-button:disabled, .names-secondary-button:disabled, .names-danger-button:disabled { cursor: not-allowed; opacity: .42; transform: none; filter: none; box-shadow: none; }') && !page.includes('.names-primary-button.names-spin-button:disabled') && page.includes('.names-wheel-stage.has-wheel-overlay .names-spin-button'), "Spin should use the standard grey disabled appearance and dim further while a centred pop-up is open");
assert(page.includes('if (randomiserMethod === "Rows" && segments.length) setSlotPosition((current) => current + .004);') && page.includes('else if (randomiserMethod === "Wheel") setRotation((current) => current + .3);') && page.includes('if (spinning || winner || pendingRemoval || dialog || reducedMotion) return undefined;') && page.includes('const wheelOverlayOpen = Boolean(winner || pendingRemoval || dialog);') && page.includes('const wheelLocked = spinning || wheelOverlayOpen;') && page.includes('const removable = !segment.preview && !locked;'), "Wheel and Rows should each idle slowly but fully freeze behind centred action popovers");
assert(page.includes('CORE.RANDOMISER_METHODS.map') && page.includes('<span>{randomiserMethod}</span>') && page.includes('setRandomiserMethod(method)') && page.includes('segmentColour, randomiserMethod }));'), "The toolbar should offer and remember the current Wheel or Slots method immediately after Customise");
assert(page.includes('profileUsesSharedSettings={false} profileShowLabel={false}') && shell.includes('profileShowLabel = true') && shell.includes('subtitle && React.createElement("p"'), "The Name Randomiser QR pop-up should omit the level label while other activities keep it by default");
assert(!page.includes('names-method-chevron') && !page.includes('aria-hidden="true">▼'), "The method button should not display a drop-down arrow");
assert(page.includes('src={randomiserMethod === "Wheel" ? ASSET.wheel : ASSET.slots}') && page.includes('className="names-method-button-glyph"') && page.includes('.names-method-button-glyph { display: block; width: 26px; height: 26px;'), "The method toolbar button should show the selected Wheel or Slots glyph to the left of its label");
assert(page.includes('className="hub-menu-anchor names-method-anchor relative"') && page.includes('{methodOpen && <window.MLH.MenuPanel title="Randomiser"') && page.includes('.names-method-anchor > .hub-menu-panel-level { width: min(300px, calc(100vw - 48px)); max-width: 300px; }'), "The Randomiser choices should use their original compact anchored menu");
assert(page.includes('const textRadius = count === 1 ? 140 :') && page.includes('.names-wheel-segment:focus { outline: none; }'), "A single name should sit clear of the centre dot without showing an oversized SVG focus outline");
assert(!page.includes('MUSIC_BORDER_GLYPHS') && !page.includes('names-wheel-segment-symbol') && !page.includes('segmentSymbol') && !page.includes('function MusicNoteBorder') && !page.includes('names-wheel-crotchet'), "Wheel names should not display musical notation");
assert(!page.includes('label="Symbols"') && !page.includes('borderSymbols') && !page.includes('names-border-toggle-glyph'), "Decorative symbols should remain permanently enabled without a Customise toggle or saved preference");
assert(page.includes('className="names-slots-row-content"') && !page.includes('rowSymbol') && !page.includes('names-slots-row-symbol') && !page.includes('<MusicNoteBorder shape="square" />'), "Slots names should not display musical notation");
assert(page.includes('.names-slots-row-content { display: flex; width: 100%; height: 100%;') && page.includes('align-items: center; justify-content: center;') && page.includes('.names-slots-row.is-removable:hover .names-slots-row-name, .names-slots-row.is-removable:focus-visible .names-slots-row-name { text-decoration: line-through;'), "Slots names should remain centred while retaining their removal feedback");
assert((page.match(/names-slots-corner-clef is-/g) || []).length === 4 && page.includes('.names-slots-corner-clef { pointer-events: none; position: absolute; z-index: 4; color: #000; font-family: "Bravura", serif; font-size: 36px;') && page.includes('opacity: 1;') && page.includes('.names-slots-corner-clef.is-top-left { top: 28px; left: 20px; transform: rotate(20deg); }') && page.includes('.names-slots-corner-clef.is-top-right { top: 28px; right: 20px; transform: rotate(-20deg); }') && page.includes('.names-slots-corner-clef.is-bottom-left { bottom: 18px; left: 20px; transform: rotate(-20deg); }') && page.includes('.names-slots-corner-clef.is-bottom-right { right: 20px; bottom: 18px; transform: rotate(20deg); }'), "Slots should show four solid-black Bravura treble clefs, with the upper pair positioned 10px lower and all four mirrored inward");
assert(page.includes('wheel: "wheel2.svg"') && page.includes('slots: "slots.svg"') && page.includes('className="names-method-badge"') && page.includes('src={method === "Wheel" ? ASSET.wheel : ASSET.slots}') && page.includes('className="names-method-label"') && page.includes('{active && <img src={ASSET.tick}') && !page.includes('randomiserMethod === method ? "✓"'), "Method choices should match the Level menu card pattern, use wheel2.svg and slots.svg, and show tick.svg for the active method");
assert(page.includes('.names-method-option { width: 100%; border: 1px solid #d6d3d1; border-radius: 12px; background: #f5f5f4;') && page.includes('.names-method-option[aria-pressed="true"] { border-color: #a8a29e; background: #e7e5e4; }') && page.includes('.names-method-badge { display: flex;') && page.includes('background: white;'), "Method choices should place their white glyph containers inside visibly grey option cards");
assert(page.includes('.names-page .hub-toolbar .names-method-option { height: auto !important; min-height: 64px !important; }') && page.includes('.names-method-option-inner { display: flex; min-height: 46px;') && page.includes('padding: 8px 12px;'), "Grey method cards should override the toolbar's 44px control height and fit each 46px white glyph container with default vertical padding");
assert(page.includes('save: "save.svg"') && page.includes('src={ASSET.save}') && page.includes('className="names-toolbar-save-glyph"') && page.includes('.names-toolbar-save-glyph { display: block; width: 21px; height: 21px;') && !page.includes('names-toolbar-chevron'), "The direct Save button should show a compact save.svg to the left of its label without a chevron");
assert(page.includes('function SlotMachine(') && page.includes('Array.from({ length: 7 }') && page.includes('rowIndex - 3') && page.includes('names-slots-window::before') && page.includes('names-slots-window::after') && page.includes('linear-gradient(to bottom') && page.includes('linear-gradient(to top'), "Slots should display five useful scrolling rows with soft white fades above and below");
assert(page.includes('.names-wheel-wrap { position: relative; width: auto; height: min(calc(100% - 24px), 850px); max-width: 100%; aspect-ratio: 1; margin: 0 auto; }') && page.includes('.names-slots-wrap { position: relative; width: auto; height: min(calc(100% - 24px), 850px); max-width: 100%; aspect-ratio: 1; margin: 0 auto; }'), "Wheel and Slots should use identical outer frames so the Spin button and pointer do not move between methods");
assert(page.includes('const MIN_SPIN_DURATION = 6000;') && page.includes('cubic-bezier(.08,.68,.12,1)') && page.includes('function animateSlots(start, target, duration)') && page.includes('1 - Math.pow(1 - progress, 4)') && page.includes('nextSegments.length * 6 + slotDelta') && page.includes('setSlotPosition(nextSegments.length * 2 + chosenIndex)'), "Wheel and Slots should decelerate gradually before stopping with the fairly chosen name beside the pointer");
assert(page.includes('const rowColour = colourPalette[segmentIndex % colourPalette.length];') && page.includes('color: segmentTextColour(rowColour)') && page.includes('fontSize = Math.max(17, 36 - distance * 7)'), "Rows should cycle through the selected colour palette, retain readable text, and enlarge the name nearest the pointer");
assert(!page.includes("Saved lists will appear here") && page.includes('border-dashed border-stone-300 bg-white px-3 py-5 text-center">Empty</p>'), "Saved Lists should show only the dotted Empty state when no lists have been saved");
assert(page.includes('edit: "rename.svg", bin: "bin.svg"') && page.includes('className="names-saved-row"') && page.includes('className={`names-saved-card ${list.id === activeSavedId ? "is-active" : ""}`}') && page.includes('aria-label={`Load ${list.title}, ${list.segments.length}') && page.includes('list.id === activeSavedId && <img src={ASSET.tick}') && page.includes('className="names-saved-title">{list.title}</span>') && page.includes('className="names-saved-count">{list.segments.length}') && page.includes('aria-label={`Edit ${list.title}`}') && page.includes('src={ASSET.edit}') && page.includes('aria-label={`Delete ${list.title}`}') && page.includes('src={ASSET.bin}') && !page.includes('className="grid grid-cols-3 gap-1.5"'), "Each saved-class card should load when selected, show a tick beside the active class, keep its name count on the same line and place labelled Edit and Delete buttons beside it");
assert(page.includes('.names-saved-list { display: flex; max-height: 300px; flex-direction: column; gap: 8px; overflow-y: auto; padding: 8px; }'), "The scrollable Saved Lists area should leave enough internal space for its button lift and shadow animations");
assert(page.includes('.names-saved-count { flex: none; color: #78716c; font-size: 14px; font-weight: 400; white-space: nowrap; }'), "Saved-list name counts should match the Name field's 14px regular-weight text");
assert(page.includes('names-main !min-h-[740px]') && page.includes('.names-main { display: flex; flex-direction: column; }') && page.includes('min-height: 610px; flex: 1;') && page.includes('height: min(calc(100% - 24px), 850px);') && !page.includes("wheelPanelHeight") && !page.includes("matchWheelHeight") && !page.includes("ResizeObserver"), "The wheel panel should fill the main container to its default padding through a stable flex layout");
const wheelStageRule = page.match(/\.names-wheel-stage \{([^}]*)\}/)?.[1] || "";
assert(wheelStageRule.includes("position: relative") && !/border(?!-box)|background|box-shadow|border-radius/.test(wheelStageRule), "The wheel stage should retain its layout without a grey nested panel, border or shadow");
assert(page.includes('})}\n        {count > 0 && <g aria-hidden="true">') && page.includes('<circle cx="300" cy="300" r="36" fill="#fff" stroke="#111" strokeWidth="1.25" />') && page.includes('className="names-wheel-centre-glyph"') && page.includes('transform="translate(0 7)"') && page.includes('{"\\uE050"}</text>') && page.includes('.names-wheel-centre-glyph { font-family: "Bravura", serif; font-size: 34px;'), "A larger outlined white centre circle containing a Bravura treble clef should rotate with the wheel, sit at its approved optical height and appear only when it contains a name");
assert(page.includes('.names-page > header > div { max-width: 1500px; }') && page.includes('names-page`}>'), "The Name Randomiser header should share the wider main-container alignment");
assert(!page.includes("names-spin-note"), "The add-name instruction should not be repeated beneath the wheel");
assert(page.includes('const displayedSegments = previewName ? [...segments, { id: "draft-preview"') && page.includes('<Wheel segments={displayedSegments}'), "Typing should display a live preview segment before Add is pressed");
assert(page.includes('setDraftName(CORE.capitaliseNameInput(event.target.value))') && page.includes('autoCapitalize="words"'), "The name field should capitalise the first letter of every entered word");
assert(page.includes('.names-toolbar-name { font-size: 14px; font-weight: 400; }') && page.includes('.names-primary-button.names-toolbar-add { font-size: 14px; font-weight: 600; }'), "The Name field should use regular-weight text while Add retains the Customise control's semibold typography");
assert(page.includes('.names-page .hub-toolbar button, .names-page .hub-toolbar input { height: 44px !important; min-height: 44px !important; box-sizing: border-box; }') && page.includes('.names-saved-actions button { box-sizing: border-box; height: 44px !important; min-height: 44px !important; }'), "Customise, Name, Add, Saved Lists, Save and Clear should share an exact 44px control height");
assert(page.includes('.names-add-group { position: absolute; left: 50%; display: flex; align-items: flex-start; gap: 8px; transform: translateX(-130px); }') && page.includes('className="names-add-group" role="group" aria-label="Add Name"'), "The centre of the 260px Name field should align exactly with the centre of the main toolbar container while allowing validation text beneath it");
assert(page.includes('const nextSegments = clean ? [...segments, { id: uid("segment"), names: [clean] }] : segments;') && page.includes('if (clean) {\n      setSegments(nextSegments);\n      setDraftName("");\n      setDuplicateErrorKey(0);') && page.includes('spinDisabled={wheelLocked || displayedSegments.length < 2 || Boolean(cleanDraftName && !previewName)}'), "Spin should automatically commit a valid unadded name before choosing from the completed list, while still blocking duplicates and lists with fewer than two names");
assert(page.includes('className={`names-wheel-segment ${segment.preview ? "is-preview" : ""} ${removable ? "is-removable"') && page.includes('.names-wheel-segment.is-removable:hover .names-segment-label { text-decoration: line-through;') && page.includes('if (event.pointerType === "touch")') && page.includes('if (armedRemoveId === segment.id)') && page.includes('role={!segment.preview ? "button" : undefined}') && page.includes('event.key === "Enter" || event.key === " "') && page.includes('<text className="names-segment-label"') && !page.includes("names-remove-control"), "Each complete segment should provide hover strike-through, two-tap touch removal and accessible keyboard removal");
assert(page.includes('className={`${window.MLH.ToolbarButtonClass} names-toolbar-clear sm:min-w-[92px]`}') && page.includes('>Clear</button>') && page.includes('.names-toolbar-clear { border-color: #d6d3d1 !important; background: #fff !important; color: #000 !important; }') && !page.includes("names-wheel-clear") && !page.includes("Current wheel"), "Clear should use a white fill with black text and the same explicit width as Save");
assert(page.includes('@media (min-width: 640px) { .names-toolbar-save, .names-toolbar-clear { width: 92px; } }'), "Save and Clear should have matching desktop widths");
assert(page.includes('right={<div className="flex items-center gap-2">') && page.includes('>Clear</button>') && page.includes('<div className="names-saved-actions">') && page.includes('.names-saved-actions { position: absolute; z-index: 5; right: 0; bottom: 0;') && page.includes('.names-saved-actions .hub-menu-panel { top: auto; bottom: 100%;') && page.includes('ref={savedListsRef}') && page.includes('list: "list.svg"') && page.includes('className="names-toolbar-list-glyph"') && page.includes('<span>Saved Classes</span>') && page.includes('{savedListsOpen && <window.MLH.MenuPanel title="Saved Classes"') && page.includes('names-toolbar-save gap-2 sm:min-w-[92px]') && page.includes('disabled={wheelLocked || !segments.length} onClick={() => { setCustomiseOpen(false); setMethodOpen(false); setSavedListsOpen(false); requestSave(); }}') && page.includes('<span>Save</span>') && page.includes('.names-toolbar-save { border-color: #000 !important; background: #000 !important; color: #fff !important; }') && page.indexOf('>Clear</button>') < page.indexOf('<div className="names-saved-actions">') && page.indexOf('<span>Saved Classes</span>') < page.indexOf('<span>Save</span>') && !page.includes('<section className="names-panel mt-3" aria-labelledby="saved-lists-title">'), "Clear should remain in the toolbar while Saved Classes and Save align with its right edge at the bottom-right of the main panel, with Saved Classes using its upward menu");
assert(page.includes('function WheelPopover(') && page.includes('className="names-winner-panel names-wheel-confirm-panel names-wheel-popover"') && page.includes('.names-wheel-popover { max-height: calc(100% - 40px); overflow-y: auto; }') && page.includes('{customiseOpen && <window.MLH.MenuPanel title="Customise"') && page.includes('{methodOpen && <window.MLH.MenuPanel title="Randomiser"') && page.includes('{savedListsOpen && <window.MLH.MenuPanel title="Saved Classes"') && page.includes('{dialog?.type === "save" && <WheelPopover') && page.includes('{dialog?.type === "edit" && <WheelPopover') && page.includes('{dialog?.type === "load" && <WheelPopover') && page.includes('{dialog?.type === "clear" && <WheelPopover') && page.includes('{dialog?.type === "delete" && <WheelPopover') && !page.includes('<Dialog') && !page.includes('names-overlay'), "Toolbar menus should use their original anchored displays while every action dialog keeps the centred winner-style popover");
assert(page.includes('function confirmEditList()') && page.includes('const names = CORE.uniqueNewNames(dialog?.value, []);') && page.includes('title="Edit Class"') && page.includes('value={dialog.listTitle}') && page.includes('<NumberedClassTextarea id="names-edit-class-students" rows={20} value={dialog.value}') && page.includes('onClick={confirmEditList}>Save</button>') && page.includes('if (activeSavedId === nextList.id) {') && page.includes('setSegments(CORE.copySegments(nextSegments));'), "Editing a saved class should prefill its title and students, save cleaned names and immediately synchronise an actively loaded class");
assert(page.includes('<label htmlFor="names-edit-class-name" className="names-edit-field-label">Class Name</label>') && page.includes('<input id="names-edit-class-name" className="names-field"') && page.includes('.names-edit-field-label { display: block; margin: 14px 0 6px;'), "The Edit Class name field should have a visible, accessible Class Name heading");
assert(page.includes('Edit the class name and students below, with one student on each line.') && page.includes('placeholder="Class name"') && page.includes('error: !title ? "Enter a class name."'), "Edit Class should consistently refer to the saved title as a class name");
assert(page.includes('function NumberedClassTextarea(') && page.includes('Students ({count})') && page.includes('<NumberedClassTextarea id="names-edit-class-students" rows={20}') && page.includes('<NumberedClassTextarea id="names-add-class-students" autoFocus value={dialog.value} existingSegments={segments}'), "Add Class and Edit Class should show live unique-student totals, with Add Class excluding existing names and Edit Class requesting 20 visible names");
assert(page.includes('className={`names-numbered-textarea ${rows === 20 ? "is-edit-class" : ""} ${value ? "" : "is-empty"}`}') && page.includes('.names-numbered-textarea.is-edit-class .names-class-textarea { height: 420px; min-height: 220px; max-height: calc(100dvh - 580px); }'), "Edit Class should show up to 20 names while shrinking its Students field enough to keep the dialog actions visible");
assert(page.includes('className="names-class-line-numbers" aria-hidden="true"') && page.includes('number || "\\u00a0"') && page.includes('gutterRef.current.scrollTop = event.currentTarget.scrollTop') && page.includes('wrap="off"'), "Class textareas should show visual grey line numbers aligned with their independently scrolling names");
assert(page.includes('box-sizing: border-box; width: 40px;') && page.includes('padding: 11px 0 11px 14px;') && page.includes('text-align: left;'), "Single- and double-digit student numbers should share the same left edge");
assert(page.includes('${value ? "" : "is-empty"}') && page.includes('.names-numbered-textarea.is-empty .names-class-textarea { padding-left: 12px; }'), "An empty class field should left-align its example text until numbering is needed");
assert(page.includes('.names-class-textarea { box-sizing: border-box; min-height: 190px; resize: vertical; padding-top: 11px; padding-bottom: 11px; line-height: 1.45; overscroll-behavior-y: contain; }'), "Class-list text areas should contain scroll movement instead of passing it to the page at their limits");
assert(page.includes('const textRadius = count === 1 ? 140 : (4 * 260 * Math.sin(sliceRadians / 2)) / (3 * sliceRadians);') && page.includes('x={textX} y="300" transform={`rotate(180 ${textX} 300)`}'), "Every flipped name label should use the visual centre of its dynamically sized segment, with a single name kept clear of the centre dot");
assert(page.includes('.names-toolbar-name { width: 260px; }') && page.includes('.names-toolbar-add { width: 92px; min-width: 92px; }') && page.includes('.names-spin-button { min-width: 110px; min-height: 58px; height: 58px;') && page.includes('feedback={<NameComposer draftName={draftName} setDraftName={setDraftName} addName={addName} duplicateErrorKey={duplicateErrorKey}') && page.includes('<div className="names-wheel-pointer-group">\n      <button type="button" className="names-primary-button names-spin-button"') && page.includes('onSpin={performSpin} spinDisabled={wheelLocked || displayedSegments.length < 2 || Boolean(cleanDraftName && !previewName)}'), "The wider Add Name controls should use the centre toolbar section while Add matches Save's width and Spin matches the pointer's height");
assert(page.includes('if (CORE.hasName(segments, clean))') && page.includes('Name already added!') && page.includes('@keyframes namesDuplicateShake') && page.includes('className="names-duplicate-message" role="alert"'), "A repeated single name should be blocked with an accessible shaking red message beneath the Name field");
assert(page.includes('.names-duplicate-message { position: absolute; top: calc(100% + 7px); left: 0; width: 100%;') && page.includes('text-align: center; white-space: nowrap; animation: namesDuplicateShake'), "The duplicate-name warning should be centred beneath the Name field and sit 3px lower");
assert(page.includes('if (duplicateErrorKey > 0 && !CORE.hasName(segments, draftName)) setDuplicateErrorKey(0);'), "A duplicate warning should disappear automatically when its conflicting pupil is removed");
assert(page.includes('<window.MLH.MenuSubheading>Options</window.MLH.MenuSubheading>') && page.includes('<span>Add Class</span>') && page.includes('<window.MLH.MenuSubheading>Audio</window.MLH.MenuSubheading>') && page.includes('<window.MLH.MenuSubheading>Colour</window.MLH.MenuSubheading>') && page.includes('classIcon: "class.svg"') && page.includes('src={ASSET.classIcon}') && page.includes('.names-customise-action-icon { display: block; width: 23px; height: 23px; flex: none; object-fit: contain; filter: invert(1); transform: translateX(-2px); }') && page.includes('.names-customise-action { width: 100%; }') && page.includes('body > .hub-menu-panel-customise .hub-menu-title { margin-bottom: 0; }') && page.includes('.names-colour-picker { margin-top: 0; }'), "Customise should tighten the title spacing and use the Hub's uppercase section headings with a full-width black Add Class action, class.svg shifted 2px left and no colour divider");
assert((page.match(/className="names-customise-section"/g) || []).length === 3 && page.includes('.hub-menu-panel-customise .names-customise-section { display: flex; flex-direction: column; gap: 6px; }') && page.includes('.hub-menu-panel-customise .names-customise-section + .names-customise-section { margin-top: 12px; }') && page.includes('.hub-menu-panel-customise .names-customise-section .hub-toggle-row { margin-bottom: 0; }'), "Customise headings should use equal gaps to their controls and equal spacing between sections");
assert(page.includes('{dialog?.type === "add-class" && <WheelPopover title="Add Class"') && page.includes('one student on each line') && page.includes('CORE.uniqueNewNames(dialog?.value, segments)') && page.includes('duplicate${skipped === 1 ? "" : "s"} skipped'), "Add Class should accept pasted line-separated names, add unique students and report skipped duplicates");
assert(page.includes('setSegments((current) => [...current, ...names.map((name) => ({ id: uid("segment"), names: [name] }))]);\n    setDraftName("");\n    setDuplicateErrorKey(0);'), "A successful class import should clear any stale single-name draft and validation message");
assert(page.includes("placeholder={'For example:\\nEmma\\nLewis\\nSophie\\nCallum\\nAisha'}"), "The Add Class field should demonstrate five varied pupil names on separate lines");
assert(page.includes('fullscreen: "full screen.svg"') && page.includes('mainRef.current?.requestFullscreen()') && page.includes('document.exitFullscreen()') && page.includes('document.addEventListener("fullscreenchange"') && page.includes('const FULLSCREEN_CONTROL_TIMEOUT = 3000;') && page.includes('document.addEventListener("mousemove", revealControl') && page.includes('document.addEventListener("touchstart", revealControl') && page.includes('document.addEventListener("keydown", revealControl)') && page.includes('className={`names-fullscreen-action ${isFullscreen && !fullscreenControlVisible ? "is-hidden" : ""}`}') && page.includes('.names-fullscreen-action.is-hidden { pointer-events: none; opacity: 0; }') && page.includes('.names-main:fullscreen .hub-toolbar, .names-main:fullscreen .names-saved-actions { display: none !important; }'), "The bottom-left full-screen control should use the supplied glyph, exit by button or Escape, fade after three inactive seconds, return on pointer, touch or keyboard activity, and leave only Spin and itself visible among the normal controls");
assert(page.includes('className={`names-wheel-stage ${randomiserMethod === "Rows" ? "is-rows" : "is-wheel"}') && page.includes('.names-main:fullscreen .names-wheel-stage.is-rows .names-slots-wrap { transform: translateX(60px); }') && page.includes('.names-main:fullscreen .names-wheel-stage.is-rows .names-winner-panel { left: calc(50% + 60px); }'), "Full-screen Rows should centre the complete Spin, pointer and row-box arrangement while keeping its popovers aligned with the shifted box");
assert(page.includes('.names-main:fullscreen .names-wheel-stage.is-wheel .names-wheel-wrap { transform: translateX(60px); }') && page.includes('.names-main:fullscreen .names-wheel-stage.is-wheel .names-winner-panel { left: calc(50% + 60px); }'), "Full-screen Wheel should use the same complete-group centring and popover alignment as Rows");
assert(page.indexOf('<Confetti activeKey={confettiKey} />') > page.indexOf('<main ref={mainRef}') && page.indexOf('<Confetti activeKey={confettiKey} />') < page.indexOf('</main>'), "Confetti should render inside the element that enters full screen so celebrations remain visible in both display modes");
assert(page.includes('button:focus-visible { outline-color: rgba(0,0,0,.45); }') && page.includes('.names-field:focus-visible { border-color: #111; box-shadow: 0 0 0 3px rgba(0,0,0,.16); }') && !page.includes('.names-field:focus-visible { border-color: #16a34a;'), "Name Randomiser button and field focus highlights should use black rather than green");
assert(page.includes('<circle cx="300" cy="300" r="260" fill="#fff" stroke="#111" strokeWidth="1.25" />') && page.includes('strokeWidth={count > 35 ? .75 : 1.25}'), "The wheel outline and segment boundaries should remain visible without appearing heavy");
assert(page.includes('.names-empty-title { color: #111; font-size: 28px; font-weight: 800;') && page.includes('.names-empty-description { margin-top: 4px; color: #a8a29e; font-size: 14px; font-weight: 400;') && page.includes('<span className="names-empty-title">Welcome!</span><span className="names-empty-description">Add a name to get started.</span>'), "The empty-state welcome should match Spin text sizing while its instruction matches the Name field placeholder");
assert(!page.includes(">+ Add another name</button>") && !page.includes(">Add to wheel</button>") && !page.includes("Add another box to put a pair or group"), "The Add Name panel should use the approved simplified controls");
assert(page.includes("Loading") && page.includes("will replace the current wheel"), "Loading a saved list should warn before replacing the wheel");
assert(page.includes("Saved lists will not be affected"), "Clearing the current wheel must not delete saved lists");
assert(page.includes('className="names-primary-button" onClick={() => { setSegments([]); setActiveSavedId(null); setDraftName(""); setDuplicateErrorKey(0); setDialog(null); setStatus("Wheel cleared."); }}>Clear</button>') && page.includes('className="names-primary-button" onClick={() => { setSavedLists((current) => current.filter'), "Clear and Delete confirmations should both use black primary action buttons");
assert(page.includes('setActiveSavedId(list.id); setDraftName(""); setDuplicateErrorKey(0); setDialog(null);') && !page.includes('setActiveSavedId(null);\n    setDialog(null);\n    const skipped'), "Loading should clear stale draft validation while Add Class preserves the current saved-list association");
assert(!page.includes('.names-panel {') && !page.includes('.names-panel-title {'), "Unused legacy panel styles should stay removed");
assert(page.includes('colour.value === CORE.MULTI_SEGMENT_COLOUR') && page.includes('conic-gradient(${CORE.MULTI_SEGMENT_PALETTE.join(", ")})') && page.includes('./name-randomiser-core.js?v=20260722-multi-white-arrow'), "The first and default Multi option should use a multicolour swatch and the latest core cache label");

assert(index.includes('"Name Randomiser": "names-icon.svg"'), "The Hub should map the supplied Name Randomiser icon");
assert(index.includes('href: "name-randomiser.html", title: "Name Randomiser"'), "The Name Randomiser should appear in the Hub app data");
assert(index.includes('audio: true, disabled: [], direct: true'), "The Name Randomiser card should open directly without qualification levels");
assert(index.includes('data-direct="${app.direct === true}"') && index.includes('if (card.dataset.direct === "true")'), "Direct Hub cards should bypass the level picker while retaining the normal card layout");
assert(index.includes('<span class="arrow"><svg'), "Direct Hub cards should retain the shared chevron");
assert(index.indexOf('{ category: "Other"') < index.indexOf('href: "name-randomiser.html"'), "The Name Randomiser should be listed under Other");

console.log("Name Randomiser integration tests passed.");
