(function (root) {
  "use strict";
  const audio = (question, markers = []) => { const track = String(question + 1).padStart(2, "0"); return { file: `../exampapers/higher/2025/Music H 2025 - Track ${track}-1.mp3`, label: "Question audio", maxPlaysExam: 1, markers }; };
  const option = (value, label = value) => ({ value, label });
  const concept = (label, answers, correct = false, options = {}) => ({ label, answers: answers || [label], correct, ...options });

  const paper = {
    id: "higher-2025", title: "Higher Music 2025", level: "Higher", levelCode: "H", year: 2025,
    totalMarks: 40, openingInstructions: ["Total marks — 40", "Attempt ALL questions"], estimatedMinutes: 60,
    sourcePath: "../exampapers/higher/2025/Music H 2025 Paper.pdf", markingInstructionsPath: "../exampapers/higher/2025/Music H 2025 Answers.pdf",
    attribution: "Original question paper and audio content © Qualifications Scotland. Interactive adaptation created independently for non-commercial educational use. This resource is not endorsed by Qualifications Scotland.",
    questions: [
      {
        id: "q1", number: "1", marks: 4, topic: "Instrumental music", audio: { clips: [audio(1, [{ label: "(a) 1st", time: 43.02 }, { label: "(a) 2nd", time: 127.04 }, { label: "(b)", time: 241.3 }])] }, intro: "This question features instrumental music.",
        subquestions: [
          { id: "q1a", label: "(a)", marks: 3, type: "concept-lines", letteredConcept: true, lines: 3, requiredResponses: 3, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify three concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your three answers on the lines below.", boldPhrases: ["three"], conceptBank: [concept("Pedal"), concept("Impressionist"), concept("Modulation", ["modulation", "key change", "change of key"], true), concept("Passacaglia"), concept("Basso continuo", ["basso continuo"], true), concept("Ripieno", ["ripieno"], true), concept("Interrupted cadence"), concept("Modal"), concept("Oboe")], beforeAnswerLines: ["The music will be played twice with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], answerDisplay: "Basso continuo, Modulation and Ripieno", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q1b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and identify the type of work.", acceptedAnswers: ["sonata", "piano sonata"], alwaysBlockedAnswers: ["sonata form"], answerDisplay: "Sonata or piano sonata", definition: "Sonata form on its own is not accepted." },
        ],
      },
      {
        id: "q2", number: "2", marks: 5, topic: "Musical guide", audio: { clips: [audio(2, [{ label: "1st", time: 70.92 }, { label: "2nd", time: 156.6 }, { label: "3rd", time: 242.72 }])] }, layout: "higher-guide",
        intro: ["In this question you will hear instrumental music.", "A guide to the music is shown below. You are required to complete this guide by inserting music concepts.", "There will now be a pause of 30 seconds to allow you to read through the question.", "The music will be played three times with a pause of 20 seconds between playings. You will then have a further 30 seconds to complete your answer.", "In the first two playings a voice will help guide you through the music.", "There is no voice in the third playing.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introCompactRange: [6, 8],
        subquestions: [
          { id: "q2a", label: "1.", marks: 1, type: "short-text", inlineAnswer: { before: "The ornament is a/an", after: "." }, acceptedAnswers: ["trill"], answerDisplay: "Trill", definition: "The ornament is a trill." },
          { id: "q2b", label: "2.", marks: 1, type: "short-text", inlineAnswer: { before: "A prominent rhythmic feature is", after: "." }, acceptedAnswers: ["syncopation", "syncopated", "ostinato"], answerDisplay: "Syncopation or ostinato", definition: "Either accepted rhythmic feature earns the mark." },
          { id: "q2c", label: "3.", marks: 1, type: "short-text", inlineAnswer: { before: "The ornament is a/an", after: "." }, acceptedAnswers: ["acciaccatura"], answerDisplay: "Acciaccatura", definition: "The ornament is an acciaccatura." },
          { id: "q2d", label: "4.", marks: 1, type: "short-text", inlineAnswer: { before: "The melody is played by a/an", after: "." }, acceptedAnswers: ["saxophone", "sax", "alto saxophone", "alto sax", "tenor saxophone", "tenor sax", "soprano saxophone", "soprano sax", "baritone saxophone", "baritone sax"], answerDisplay: "Any type of saxophone", definition: "Any clearly identified type of saxophone is accepted." },
          { id: "q2e", label: "5.", marks: 1, type: "short-text", inlineAnswer: { before: "The cadence is", after: "." }, acceptedAnswers: ["imperfect", "imperfect cadence"], answerDisplay: "Imperfect cadence", definition: "The cadence is imperfect." },
        ],
      },
      {
        id: "q3", number: "3", marks: 4, topic: "Contrasting styles", audio: { clips: [audio(3, [{ label: "(a)", time: 7.02 }, { label: "(b) 1st", time: 53.64 }, { label: "(b) 2nd", time: 73.88 }, { label: "(c)", time: 98.86 }, { label: "(d) 1st", time: 169.36 }, { label: "(d) 2nd", time: 193.3 }])] }, intro: "This question features music in contrasting styles.",
        subquestions: [
          { id: "q3a", label: "(a)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to this excerpt and describe the style.", acceptedAnswers: ["plainchant", "plainsong", "gregorian chant"], answerDisplay: "Plainchant or plainsong", definition: "The style is plainchant." },
          { id: "q3b", label: "(b)", marks: 1, type: "radio", promptLines: ["Listen to this excerpt and tick one box to describe what you hear.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the excerpt for the first time.", "Here is the excerpt for the second time."], options: ["Added 6th", "Diminished 7th", "Dominant 7th", "Minor"].map(value => option(value)), answer: "Diminished 7th", answerDisplay: "Diminished 7th", definition: "The outlined chord is a diminished 7th." },
          { id: "q3c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and describe the time signature.", acceptedAnswers: ["irregular time signature", "irregular time signatures", "irregular", "time changes", "5/4", "5 4", "five beats", "5 beats", "five beats in the bar", "5 beats in the bar"], answerDisplay: "Irregular time signature, time changes or 5/4", definition: "Any response indicating five beats in the bar is accepted." },
          { id: "q3d", label: "(d)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a new excerpt and write the concept to describe the rhythmic feature you hear.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the excerpt for the first time.", "Here is the excerpt for the second time."], acceptedAnswers: ["diminution"], answerDisplay: "Diminution", definition: "The rhythmic feature is diminution." },
        ],
      },
      {
        id: "q4", number: "4", marks: 6, topic: "Music literacy", audio: { clips: [audio(4, [{ label: "Guide", time: 11.52 }, { label: "2nd", time: 211.88 }, { label: "3rd", time: 294.78 }, { label: "4th", time: 378.58 }])] },
        intro: ["This question is based on a popular song.", "Listen to the excerpt and follow the guide to the music below.", "Here is the music for the first time.", "You now have 2 minutes to read the question."],
        outro: ["During the next three playings complete your answers (a) to (f).", "All answers must be written in the score above.", "The music will be played three more times with a pause of 30 seconds between playings and a pause of 2 minutes before the next question starts.", "Here is the music for the second time.", "Here is the music for the third time.", "Here is the music for the fourth time."], outroBoldPhrases: ["three", "All answers must be written in the score above."], outroCompactRange: [3, 5], outroPosition: "before-score",
        score: { key: "G major", timeSignature: "4/4", bars: 24, sharedNotation: "higher-2025-q4" }, scorePosition: "before",
        subquestions: [
          { id: "q4a", label: "(a)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-select", inlineNotationControls: true, prompt: "The key of the music is G major. Draw a circle around the subdominant note in bar 3.", options: [], answer: "bar-3-c", answerDisplay: "The C note in bar 3", definition: "C is the subdominant note in G major." },
          { id: "q4b", label: "(b)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Name the chords played in bars 7 and 8. You may use letter names or numbers. The chord in bar 6 is given.", answerReference: { heading: "Choose from the following", rows: [["G", "Chord I"], ["C", "Chord IV"], ["D", "Chord V"], ["Em", "Chord VI"]], footer: "Insert your answers in the boxes provided." }, acceptedAnswers: ["d em", "d, em", "d e minor", "d, e minor", "v vi", "v, vi", "5 6", "5, 6"], answerDisplay: "D and Em; V and VI; or 5 and 6", definition: "Both chords must be correct." },
          { id: "q4c", label: "(c)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Transpose the boxed notes in bar 11 one octave lower into the bass clef. Use the stave given.", options: [], noteSlots: 5, answer: "B3,C4,B3,A3,G3", answerDisplay: "B3 quaver, C4 quaver, B3 crotchet, A3 quaver and G3 quaver", definition: "The pitch and rhythm of all five notes must be correct; the slur is optional." },
          { id: "q4d", label: "(d)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Insert the missing notes in bar 17. The rhythm is given.", options: [], noteSlots: 2, answer: "D5,C5", answerDisplay: "D5 quaver followed by C5 quaver", definition: "The pitch and rhythm of both notes must be correct." },
          { id: "q4e", label: "(e)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "bar-line", inlineNotationControls: true, prompt: "Insert the missing bar line in the last line.", options: [], answer: "after-bar-21", answerDisplay: "After bar 21", definition: "The bar line belongs between bars 21 and 22." },
          { id: "q4f", label: "(f)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Describe the interval formed by the two notes in the box in bar 23.", acceptedAnswers: ["4", "4th", "fourth", "perfect 4th", "perfect fourth"], answerDisplay: "4th", definition: "Any description of a fourth is accepted." },
        ],
      },
      {
        id: "q5", number: "5", marks: 5, topic: "Instrumental music", audio: { clips: [audio(5, [{ label: "(a) 1st", time: 43.26 }, { label: "(a) 2nd", time: 127.66 }, { label: "(a) 3rd", time: 211.54 }, { label: "(b)", time: 325.68 }])] }, intro: "This question features instrumental music.",
        subquestions: [
          { id: "q5a", label: "(a)", marks: 4, type: "concept-lines", letteredConcept: true, lines: 4, requiredResponses: 4, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify four concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your four answers on the lines below.", boldPhrases: ["four"], conceptBank: [concept("Ground bass"), concept("Triplets", ["triplets", "triplet"], true), concept("Obbligato"), concept("Flute"), concept("Chromatic scale", ["chromatic scale", "chromatic"], true), concept("Concertino"), concept("Plagal cadence"), concept("Chamber music", ["chamber music"], true), concept("Tierce de Picardie"), concept("Anacrusis", ["anacrusis", "upbeat"], true)], beforeAnswerLines: ["The music will be played three times with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], answerDisplay: "Anacrusis, Chamber music, Chromatic scale and Triplets", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q5b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to this excerpt and identify the style.", acceptedAnswers: ["jazz funk", "jazz-funk"], alwaysBlockedAnswers: ["jazz", "funk"], answerDisplay: "Jazz funk", definition: "Jazz or funk on its own is not accepted." },
        ],
      },
      {
        id: "q6", number: "6", marks: 6, topic: "Listening analysis", audio: { clips: [audio(6, [{ label: "1st", time: 47.78 }, { label: "2nd", time: 122.36 }, { label: "3rd", time: 197.4 }])] },
        intro: ["This question is based on vocal music.", "In this question you should identify the most prominent concepts which are present in the music.", "As you listen, identify at least two concepts from each of the following headings:", "Style/structure", "Melody/harmony", "Rhythm/tempo", "", "You will hear the music three times and you should make notes as you listen.", "Rough work will not be marked.", "Marks will only be awarded for the final answer.", "After the third playing you will have 3 minutes to write your final answer in the space provided.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introBoldPhrases: ["two", "Style/structure", "Melody/harmony", "Rhythm/tempo", "three times", "Rough work will not be marked."], introHeadingRowRange: [3, 5], introCompactRange: [11, 13], introTotalMarks: 6, introTotalMarksIndex: 10, showPartMarks: false,
        subquestions: [{ id: "q6a", label: "Final answer", marks: 6, type: "structured-review", autoMark: true, maxMarksPerHeading: 2, minHeadingsForFullMarks: 3, roughWork: true, finalAnswerField: true, finalAnswerLines: 10, endOfPaper: false, requiredResponses: 6, prompt: "Final answer", headings: [
          { id: "style", label: "Style/structure", concepts: [{ label: "Chamber music", answers: ["chamber music"] }, { label: "Imitation", answers: ["imitation"] }, { label: "Lied", answers: ["lied"] }, { label: "Romantic", answers: ["romantic", "romanticism"] }, { label: "Through-composed", answers: ["through-composed", "through composed"] }] },
          { id: "melody", label: "Melody/harmony", concepts: [{ label: "Acciaccatura", answers: ["acciaccatura"] }, { label: "Broken chord / arpeggio", answers: ["broken chord", "arpeggio", "arpeggiated"], creditId: "arpeggio" }, { label: "Dominant 7th", answers: ["dominant 7th", "dominant seventh"] }, { label: "Major", answers: ["major", "major tonality"], alwaysBlockedAnswers: ["relative major", "major scale"] }, { label: "Pedal", answers: ["pedal", "pedal note"] }, { label: "Perfect cadence", answers: ["perfect cadence"] }, { label: "Sequence", answers: ["sequence"] }, { label: "Syllabic", answers: ["syllabic"] }] },
          { id: "rhythm", label: "Rhythm/tempo", concepts: [{ label: "Anacrusis", answers: ["anacrusis", "upbeat"] }, { label: "Andante / moderato", answers: ["andante", "moderato"] }, { label: "A tempo", answers: ["a tempo"] }, { label: "Pause", answers: ["pause", "fermata"] }, { label: "Rallentando / ritardando", answers: ["rallentando", "ritardando", "rall", "rit"] }, { label: "Rubato", answers: ["rubato"] }, { label: "Simple time / 3/4", answers: ["simple time", "3/4", "3 beats in a bar", "three beats in a bar"] }, { label: "Triplets", answers: ["triplets", "triplet"] }] },
        ], answerDisplay: "Any six valid concepts, with no more than two credited from each heading", additionalGuidance: ["Concepts are credited even when written under a different heading."] }],
      },
      {
        id: "q7", number: "7", marks: 5, topic: "Comparing music", audio: { clips: [audio(7, [{ label: "E1 1st", time: 119.86 }, { label: "E2 1st", time: 214.32 }, { label: "E1 2nd", time: 306.84 }, { label: "E2 2nd", time: 397.06 }, { label: "E1 3rd", time: 486.52 }, { label: "E2 3rd", time: 575.6 }, { label: "Column C", time: 656.06 }])] },
        intro: ["In this question you compare two excerpts of music.", "You must first identify concepts present in each excerpt and then decide which five concepts are common to both excerpts. Both excerpts will be played three times with a pause of 10 seconds between playings.", "As you listen, tick boxes in Column A and Column B to identify what you hear in Excerpt 1 and Excerpt 2.", "These columns are for rough work only and will not be marked.", "After the music has been played three times you will be given 2 minutes to decide which concepts are common to both excerpts and to tick five boxes in Column C.", "You now have one minute to read through the question.", "Here is Excerpt 1 for the first time. Remember to tick concepts in Column A.", "Here is Excerpt 2 for the first time. Remember to tick concepts in Column B.", "Here is Excerpt 1 for the second time.", "Here is Excerpt 2 for the second time.", "Here is Excerpt 1 for the third time.", "Here is Excerpt 2 for the third time.", "You now have 2 minutes to identify the five concepts common to both excerpts.", "Remember to tick five boxes only in Column C."], introBoldPhrases: ["five", "three", "Column A", "Column B", "Column C", "These columns are for rough work only and will not be marked.", "Remember to tick concepts in Column A.", "Remember to tick concepts in Column B.", "Remember to tick five boxes only in Column C."], introCompactRanges: [[6, 7], [8, 9], [10, 11]], introTotalMarks: 5, introTotalMarksIndex: 4, showPartMarks: false,
        subquestions: [{ id: "q7a", label: "", marks: 5, type: "comparison-grid", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Identify the five concepts common to both excerpts in Column C. Columns A and B are rough work only.", answers: ["Mass", "Imperfect cadence", "Time changes", "Homophonic", "Timpani"], columns: [{ id: "a", label: "Column A", sublabel: "Excerpt 1" }, { id: "b", label: "Column B", sublabel: "Excerpt 2" }, { id: "c", label: "Column C", sublabel: "5 concepts common to both" }], groups: [
          { label: "Style", concepts: [concept("Mass", ["mass"], true), concept("Oratorio"), concept("Gospel")] },
          { label: "Melody/harmony", concepts: [concept("Imperfect cadence", ["imperfect cadence", "imperfect"], true), concept("Whole-tone scale"), concept("Cluster")] },
          { label: "Rhythm/tempo", concepts: [concept("Compound time"), concept("Time changes", ["time changes"], true), concept("Syncopation")] },
          { label: "Texture/structure/form", concepts: [concept("Ritornello"), concept("Contrapuntal"), concept("Homophonic", ["homophonic", "homophony"], true)] },
          { label: "Timbre", concepts: [concept("Timpani", ["timpani"], true), concept("Coloratura"), concept("Pizzicato")] },
        ], answerDisplay: "Mass; Imperfect cadence; Time changes; Homophonic; Timpani", definition: "Only Column C is marked. Additional incorrect selections are deducted." }],
      },
      {
        id: "q8", number: "8", marks: 5, topic: "Musical theatre features", audio: { clips: [audio(8, [{ label: "1st", time: 100.84 }, { label: "2nd", time: 187.62 }, { label: "3rd", time: 274.28 }])] },
        intro: ["This question is based on a song from a musical.", "Below is a list of features which occur in the music.", "You now have one minute to read through the question.", "The song lyrics are shown in the table below. Insert each feature once in the column on the right at the point where it occurs.", "You only need to insert the underlined words."], showPartMarks: false,
        subquestions: [{ id: "q8a", label: "", marks: 5, type: "lyric-placement", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Insert the five underlined words at the point where they occur. Insert each word once only.", playbackLines: ["The music will now be played three times with a pause of 20 seconds between playings and a pause of 30 seconds at the end.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], features: [{ before: "descending chromatic scale on ", word: "con sordino", after: " trumpet" }, { before: "first example of ", word: "dominant 7th", after: " arpeggio" }, { before: "", word: "xylophone", after: "" }, { before: "first example of ", word: "hi-hat", after: " cymbals" }, { before: "", word: "tremolando", after: " begins for the first time" }], lyricLines: [
            "What can I say? I got carried away,",
            "And not just by balloon.",
            "Wonderful.",
            "They called me Wonderful.",
            "So I said, Wonderful, if you insist.",
            "I will be Wonderful.",
            "And they said, Wonderful,",
            "Believe me, it’s hard to resist,",
            "Cause it feels wonderful!",
            "They think I’m wonderful!",
            "Hey, look who’s wonderful;",
            "This corn-fed hick,",
            "Who said, It might be keen",
            "To build a town of green.",
            "And a wonderful road of yellow brick!"
          ], concepts: [{ id: "dominant7", label: "Dominant 7th", answers: ["dominant 7th", "dominant seventh", "dominant 7th arpeggio"], lines: [2] }, { id: "tremolando", label: "Tremolando", answers: ["tremolando", "tremolo"], lines: [2, 3] }, { id: "hihat", label: "Hi-hat", answers: ["hi-hat", "hi hat", "hi-hat cymbals", "hi hat cymbals"], lines: [5, 6] }, { id: "conSordino", label: "Con sordino", answers: ["con sordino", "con sordino trumpet"], lines: [7, 8] }, { id: "xylophone", label: "Xylophone", answers: ["xylophone"], lines: [15] }], answerDisplay: "Dominant 7th—line 2; Tremolando—line 2 or 3; Hi-hat—line 5 or 6; Con sordino—line 7 or 8; Xylophone—line 15", definition: "Each feature earns one mark when placed on an accepted lyric line." }],
      },
    ],
  };
  root.InteractiveExamPapers = root.InteractiveExamPapers || {};
  root.InteractiveExamPapers[paper.id] = paper;
  if (typeof module !== "undefined" && module.exports) module.exports = paper;
})(typeof window !== "undefined" ? window : globalThis);
