(function (root) {
  "use strict";
  const audio = (question, markers = []) => { const track = String(question + 1).padStart(2, "0"); return { file: `../exampapers/higher/2024/Music H 2024 - Track ${track}-1.mp3`, label: "Question audio", maxPlaysExam: 1, markers }; };
  const option = (value, label = value) => ({ value, label });
  const concept = (label, answers, correct = false, options = {}) => ({ label, answers: answers || [label], correct, ...options });

  const paper = {
    id: "higher-2024", title: "Higher Music 2024", level: "Higher", levelCode: "H", year: 2024,
    totalMarks: 40, openingInstructions: ["Total marks — 40", "Attempt ALL questions"], estimatedMinutes: 60,
    sourcePath: "../exampapers/higher/2024/Music H 2024 Paper.pdf", markingInstructionsPath: "../exampapers/higher/2024/Music H 2024 Answers.pdf",
    attribution: "Original question paper and audio content © Qualifications Scotland. Interactive adaptation created independently for non-commercial educational use. This resource is not endorsed by Qualifications Scotland.",
    questions: [
      {
        id: "q1", number: "1", marks: 4, topic: "Instrumental music", audio: { clips: [audio(1, [{ label: "(a) 1st", time: 41.66 }, { label: "(a) 2nd", time: 107.28 }, { label: "(b) 1st", time: 215.68 }, { label: "(b) 2nd", time: 242.48 }])] }, intro: "This question features instrumental music.",
        subquestions: [
          { id: "q1a", label: "(a)", marks: 3, type: "concept-lines", letteredConcept: true, lines: 3, requiredResponses: 3, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify three concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your three answers on the lines below.", boldPhrases: ["three"], conceptBank: [concept("Concertino", ["concertino"], true), concept("Through-composed"), concept("Sonata"), concept("Modal"), concept("Tremolando"), concept("Basso continuo", ["basso continuo"], true), concept("Bassoon"), concept("Passacaglia"), concept("Trill", ["trill"], true)], beforeAnswerLines: ["The music will be played twice with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], answerDisplay: "Basso continuo, Concertino and Trill", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q1b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a different excerpt.", "Identify the harmonic device at the final chord.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the excerpt for the first time.", "Here is the excerpt for the second time."], acceptedAnswers: ["tierce de picardie", "tierce de picardy", "picardy third", "picardie third"], answerDisplay: "Tierce de Picardie", definition: "The harmonic device is a Tierce de Picardie." },
        ],
      },
      {
        id: "q2", number: "2", marks: 5, topic: "Musical guide", audio: { clips: [audio(2, [{ label: "1st", time: 70 }, { label: "2nd", time: 145 }, { label: "3rd", time: 221 }])] }, layout: "higher-guide",
        intro: ["In this question you will hear instrumental music.", "A guide to the music is shown below. You are required to complete this guide by inserting music concepts.", "There will now be a pause of 30 seconds to allow you to read through the question.", "The music will be played three times with a pause of 20 seconds between playings. You will then have a further 30 seconds to complete your answer.", "In the first two playings a voice will help guide you through the music.", "There is no voice in the third playing.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introCompactRange: [6, 8],
        subquestions: [
          { id: "q2a", label: "1.", marks: 1, type: "short-text", inlineAnswer: { before: "The playing technique used by the instrument playing the melody is", after: "(Italian term)." }, acceptedAnswers: ["arco"], answerDisplay: "Arco", definition: "The Italian playing technique is arco." },
          { id: "q2b", label: "2.", marks: 1, type: "short-text", inlineAnswer: { before: "The ornament is a/an", after: "." }, acceptedAnswers: ["mordent"], answerDisplay: "Mordent", definition: "The ornament is a mordent." },
          { id: "q2c", label: "3.", marks: 1, type: "short-text", inlineAnswer: { before: "The melody features part of an ascending", after: "scale." }, acceptedAnswers: ["major", "major scale"], answerDisplay: "Major", definition: "The melody uses part of an ascending major scale." },
          { id: "q2d", label: "4.", marks: 1, type: "short-text", inlineAnswer: { before: "A rhythmic feature here is", after: "." }, acceptedAnswers: ["3 against 2", "three against two", "cross rhythm", "cross rhythms", "triplet", "triplets"], answerDisplay: "3 against 2, cross rhythms or triplets", definition: "The rhythmic feature is 3 against 2." },
          { id: "q2e", label: "5.", marks: 1, type: "short-text", inlineAnswer: { before: "The descending chord outlined is a/an", after: "." }, acceptedAnswers: ["dominant 7th", "dominant seventh", "a7", "a 7"], alwaysBlockedAnswers: ["dominant"], answerDisplay: "Dominant 7th or A7", definition: "Dominant on its own is not accepted." },
        ],
      },
      {
        id: "q3", number: "3", marks: 3, topic: "Contrasting music", audio: { clips: [audio(3, [{ label: "(a) 1st", time: 15.88 }, { label: "(a) 2nd", time: 47.6 }, { label: "(b)", time: 83.42 }, { label: "(c)", time: 133.12 }])] }, intro: "This question features contrasting music.",
        subquestions: [
          { id: "q3a", label: "(a)", marks: 1, type: "radio", promptLines: ["Listen to this excerpt and tick one box to describe what you hear.", "The music will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], options: ["Jazz funk", "Whole-tone scale", "Augmentation", "Irregular time signatures"].map(value => option(value)), answer: "Irregular time signatures", answerDisplay: "Irregular time signatures", definition: "The excerpt uses irregular time signatures." },
          { id: "q3b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and identify the style.", acceptedAnswers: ["impressionist", "impressionism"], answerDisplay: "Impressionist or Impressionism", definition: "The style is Impressionist." },
          { id: "q3c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a final excerpt and identify the style.", acceptedAnswers: ["soul", "soul music"], answerDisplay: "Soul music or soul", definition: "The style is soul music." },
        ],
      },
      {
        id: "q4", number: "4", marks: 6, topic: "Music literacy", audio: { clips: [audio(4, [{ label: "Guide", time: 11.2 }, { label: "2nd", time: 215 }, { label: "3rd", time: 302 }, { label: "4th", time: 384 }])] },
        intro: ["This question is based on a pop song.", "Listen to the excerpt and follow the guide to the music below.", "Here is the music for the first time.", "You now have 2 minutes to read the question."],
        outro: ["During the next three playings complete your answers (a) to (f).", "All answers must be written in the score above.", "The music will be played three more times with a pause of 30 seconds between playings and a pause of 2 minutes before the next question starts.", "Here is the music for the second time.", "Here is the music for the third time.", "Here is the music for the fourth time."], outroBoldPhrases: ["three", "All answers must be written in the score above."], outroCompactRange: [3, 5], outroPosition: "before-score",
        score: { key: "F major", timeSignature: "4/4", bars: 24, sharedNotation: "higher-2024-q4" }, scorePosition: "before",
        subquestions: [
          { id: "q4a", label: "(a)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Describe the interval formed by the two notes in the box in bar 3.", acceptedAnswers: ["5", "5th", "fifth", "perfect 5th", "perfect fifth"], answerDisplay: "5th", definition: "Any description of a fifth is accepted." },
          { id: "q4b", label: "(b)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "rhythm-entry", inlineNotationControls: true, prompt: "Correct the rhythm in the box in bar 6.", options: [option("dottedCrotchet", "Dot"), option("quaver", "Quaver tail")], noteSlots: 2, answer: "quaver,quaver", answerDisplay: "Two quavers", definition: "The rhythm of both notes must be correct; tails may be on either side." },
          { id: "q4c", label: "(c)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-select", inlineNotationControls: true, prompt: "The music is in the key of F major. Draw a circle around one example of the dominant note in the box in bars 9 and 10.", options: [], answer: "bar-10-c", acceptedAnswers: ["bar-10-c", "bar-10-c-second", "bar-10-c-both"], answerDisplay: "Either or both C notes in bar 10", definition: "A circle around either or both C notes earns the mark." },
          { id: "q4d", label: "(d)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Transpose the three boxed notes in bar 14 one octave lower into the bass clef. Use the blank stave.", options: [], noteSlots: 3, answer: "A3,C4,C4", answerDisplay: "A3 crotchet, C4 quaver tied to C4 crotchet", definition: "The pitch and rhythm of all three notes must be correct; the tie may be above or below." },
          { id: "q4e", label: "(e)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Name the chords played in bars 19 and 21. You may use letter names or numbers. The chord in bar 17 is given.", answerReference: { heading: "Choose from the following", rows: [["F", "Chord I"], ["B♭", "Chord IV"], ["C", "Chord V"], ["Dm", "Chord VI"]], footer: "Insert your answers in the boxes provided." }, acceptedAnswers: ["bb f", "bb, f", "b flat f", "b flat, f", "iv i", "iv, i", "4 1", "4, 1"], answerDisplay: "B♭ and F; IV and I; or 4 and 1", definition: "Both chords must be correct." },
          { id: "q4f", label: "(f)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "bar-label", inlineNotationControls: true, barLabel: "D.C.", prompt: "There is a Da capo in this excerpt. Write D.C. at the appropriate place in the music.", options: [option("D.C.")], answer: "bar-24", answerDisplay: "D.C., DC or Da capo in, below or after bar 24", definition: "The instruction must be placed at bar 24." },
        ],
      },
      {
        id: "q5", number: "5", marks: 6, topic: "Vocal music", audio: { clips: [audio(5, [{ label: "(a) 1st", time: 45.32 }, { label: "(a) 2nd", time: 132.44 }, { label: "(a) 3rd", time: 208.44 }, { label: "(b) 1st", time: 347.28 }, { label: "(b) 2nd", time: 370.4 }, { label: "(c) 1st", time: 408.4 }, { label: "(c) 2nd", time: 434.4 }])] }, intro: "This question features vocal music.",
        subquestions: [
          { id: "q5a", label: "(a)", marks: 4, type: "concept-lines", letteredConcept: true, lines: 4, requiredResponses: 4, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify four concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your four answers on the lines below.", boldPhrases: ["four"], conceptBank: [concept("Ripieno"), concept("Acciaccatura", ["acciaccatura"], true), concept("Arpeggio", ["arpeggio", "arpeggiated"], true), concept("Rubato", ["rubato"], true), concept("Coloratura"), concept("Atonal"), concept("Lied", ["lied"], true), concept("Da capo aria"), concept("Oratorio"), concept("Alberti bass")], beforeAnswerLines: ["The music will be played three times with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], answerDisplay: "Acciaccatura, Arpeggio, Lied and Rubato", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q5b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a contrasting piece of music and identify the vocal style.", "The excerpt is short and will be played twice."], beforeAnswerLines: ["Here is the excerpt for the first time.", "Here is the excerpt for the second time."], acceptedAnswers: ["recitative", "recit"], answerDisplay: "Recitative or Recit", definition: "The vocal style is recitative." },
          { id: "q5c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a different excerpt and identify the final chord.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the excerpt for the first time.", "Here is the excerpt for the second time."], acceptedAnswers: ["added 6th", "added sixth", "g6", "g 6"], answerDisplay: "Added 6th or G6", definition: "The final chord is an added 6th." },
        ],
      },
      {
        id: "q6", number: "6", marks: 6, topic: "Listening analysis", audio: { clips: [audio(6, [{ label: "1st", time: 45.32 }, { label: "2nd", time: 87.04 }, { label: "3rd", time: 147.04 }])] },
        intro: ["This question is based on instrumental music.", "In this question you should identify the most prominent concepts which are present in the music.", "As you listen, identify at least two concepts from each of the following headings:", "Style", "Melody/harmony", "Rhythm/tempo", "", "You will hear the music three times and you should make notes as you listen.", "Rough work will not be marked.", "Marks will only be awarded for the final answer.", "After the third playing you will have 3 minutes to write your final answer in the space provided.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introBoldPhrases: ["two", "Style", "Melody/harmony", "Rhythm/tempo", "three times", "Rough work will not be marked."], introHeadingRowRange: [3, 5], introCompactRange: [11, 13], introTotalMarks: 6, introTotalMarksIndex: 10, showPartMarks: false,
        subquestions: [{ id: "q6a", label: "Final answer", marks: 6, type: "structured-review", autoMark: true, maxMarksPerHeading: 2, minHeadingsForFullMarks: 3, roughWork: true, finalAnswerField: true, finalAnswerLines: 10, endOfPaper: false, requiredResponses: 6, prompt: "Final answer", headings: [
          { id: "style", label: "Style", concepts: [{ label: "Chamber music", answers: ["chamber music"] }, { label: "Classical", answers: ["classical"] }, { label: "String quartet", answers: ["string quartet"] }] },
          { id: "melody", label: "Melody/harmony", concepts: [{ label: "Contrary motion", answers: ["contrary motion"] }, { label: "Major / major tonality", answers: ["major", "major tonality", "major and minor"], alwaysBlockedAnswers: ["major scale"] }, { label: "Modulation / change of key", answers: ["modulation", "change of key", "modulation to minor"] }, { label: "Ornaments / grace notes", answers: ["ornament", "ornaments", "grace note", "grace notes"] }, { label: "Perfect cadence", answers: ["perfect cadence"] }, { label: "Relative minor", answers: ["relative minor"], alwaysBlockedAnswers: ["minor"] }] },
          { id: "rhythm", label: "Rhythm/tempo", concepts: [{ label: "Anacrusis", answers: ["anacrusis", "upbeat"] }, { label: "Compound time / 6/8 / 12/8", answers: ["compound time", "6/8", "12/8", "2 beats in the bar", "two beats in the bar"], alwaysBlockedAnswers: ["4 beats in the bar", "four beats in the bar"] }, { label: "Dotted rhythms", answers: ["dotted rhythm", "dotted rhythms"] }, { label: "Moderato / Andante / Allegretto", answers: ["moderato", "andante", "allegretto"] }] },
        ], answerDisplay: "Any six valid concepts, with no more than two credited from each heading", additionalGuidance: ["Concepts are credited even when written under a different heading."] }],
      },
      {
        id: "q7", number: "7", marks: 5, topic: "Comparing music", audio: { clips: [audio(7, [{ label: "E1 1st", time: 116.88 }, { label: "E2 1st", time: 206.88 }, { label: "E1 2nd", time: 266.88 }, { label: "E2 2nd", time: 356.88 }, { label: "E1 3rd", time: 436.64 }, { label: "E2 3rd", time: 543.84 }, { label: "Column C", time: 613.04 }])] },
        intro: ["In this question you compare two excerpts of music.", "You must first identify concepts present in each excerpt and then decide which five concepts are common to both excerpts. Both excerpts will be played three times with a pause of 10 seconds between playings.", "As you listen, tick boxes in Column A and Column B to identify what you hear in Excerpt 1 and Excerpt 2.", "These columns are for rough work only and will not be marked.", "After the music has been played three times you will be given 2 minutes to decide which concepts are common to both excerpts and to tick five boxes in Column C.", "You now have one minute to read through the question.", "Here is Excerpt 1 for the first time. Remember to tick concepts in Column A.", "Here is Excerpt 2 for the first time. Remember to tick concepts in Column B.", "Here is Excerpt 1 for the second time.", "Here is Excerpt 2 for the second time.", "Here is Excerpt 1 for the third time.", "Here is Excerpt 2 for the third time.", "You now have 2 minutes to identify the five concepts common to both excerpts.", "Remember to tick five boxes only in Column C."], introBoldPhrases: ["five", "three", "Column A", "Column B", "Column C", "These columns are for rough work only and will not be marked.", "Remember to tick concepts in Column A.", "Remember to tick concepts in Column B.", "Remember to tick five boxes only in Column C."], introCompactRanges: [[6, 7], [8, 9], [10, 11]], introTotalMarks: 5, introTotalMarksIndex: 13, showPartMarks: false,
        subquestions: [{ id: "q7a", label: "", marks: 5, type: "comparison-grid", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Identify the five concepts common to both excerpts in Column C. Columns A and B are rough work only.", answers: ["Baroque", "Melismatic", "Obbligato", "Anacrusis", "Imitation"], columns: [{ id: "a", label: "Column A", sublabel: "Excerpt 1" }, { id: "b", label: "Column B", sublabel: "Excerpt 2" }, { id: "c", label: "Column C", sublabel: "5 concepts common to both" }], groups: [
          { label: "Style", concepts: [concept("Baroque", ["baroque"], true), concept("Classical"), concept("Romantic")] },
          { label: "Melody/harmony", concepts: [concept("Melismatic", ["melismatic"], true), concept("Descant"), concept("Obbligato", ["obbligato"], true)] },
          { label: "Rhythm", concepts: [concept("Cross rhythms"), concept("Anacrusis", ["anacrusis"], true), concept("Time changes")] },
          { label: "Structure/form", concepts: [concept("Imitation", ["imitation"], true), concept("Ritornello"), concept("Passacaglia")] },
          { label: "Timbre", concepts: [concept("A cappella"), concept("Mezzo soprano"), concept("French horn")] },
        ], answerDisplay: "Baroque; Melismatic; Obbligato; Anacrusis; Imitation", definition: "Only Column C is marked. Additional incorrect selections are deducted." }],
      },
      {
        id: "q8", number: "8", marks: 5, topic: "Choral features", audio: { clips: [audio(8, [{ label: "1st", time: 104.04 }, { label: "2nd", time: 207.76 }, { label: "3rd", time: 310.76 }])] },
        intro: ["This question is based on a choral work by a contemporary composer.", "Below is a list of features which occur in the music.", "You now have one minute to read through the question.", "The song lyrics are shown in the table below. Insert each feature once in the column on the right at the point where it occurs.", "You only need to insert the underlined words."], showPartMarks: false,
        subquestions: [{ id: "q8a", label: "", marks: 5, type: "lyric-placement", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Insert the five underlined words at the point where they occur. Insert each word once only.", playbackLines: ["The music will now be played three times with a pause of 20 seconds between playings and a pause of 30 seconds at the end.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], features: [{ before: "", word: "perfect", after: " cadence" }, { before: "", word: "interrupted", after: " cadence" }, { before: "", word: "glissando", after: "" }, { before: "first example of singing in ", word: "harmony", after: "" }, { before: "", word: "male", after: " voices in unison" }], lyricLines: [
            "Instrumental",
            "Ev’ry good gift,",
            "All that we need and cherish",
            "Comes from the Lord",
            "In token of his love;",
            "We are his hands,",
            "Stewards of all his bounty;",
            "His is the earth,",
            "And his the heav’ns above:",
            "Praise to thee, O Lord,",
            "For all creation,",
            "Give us thankful hearts,",
            "That we may see:",
            "All the gifts we share,",
            "And ev’ry blessing,",
            "All things come of thee,",
            "All things come of thee."
          ], concepts: [{ id: "glissando", label: "Glissando", answers: ["glissando"], lines: [1] }, { id: "male", label: "Male", answers: ["male", "male voices", "male voices in unison"], lines: [6, 7] }, { id: "harmony", label: "Harmony", answers: ["harmony", "singing in harmony"], lines: [10] }, { id: "interrupted", label: "Interrupted", answers: ["interrupted", "interrupted cadence"], lines: [16] }, { id: "perfect", label: "Perfect", answers: ["perfect", "perfect cadence"], lines: [17] }], answerDisplay: "Glissando—line 1; Male—line 6 or 7; Harmony—line 10; Interrupted—line 16; Perfect—line 17", definition: "Each feature earns one mark when placed on an accepted lyric line." }],
      },
    ],
  };
  root.InteractiveExamPapers = root.InteractiveExamPapers || {};
  root.InteractiveExamPapers[paper.id] = paper;
  if (typeof module !== "undefined" && module.exports) module.exports = paper;
})(typeof window !== "undefined" ? window : globalThis);
