(function (root) {
  "use strict";

  const audio = (question, markers = []) => {
    const track = String(question + 1).padStart(2, "0");
    return { file: `../exampapers/higher/2022/Music H 2022 - Track ${track}-1.mp3`, label: "Question audio", maxPlaysExam: 1, markers };
  };
  const option = (value, label = value) => ({ value, label });
  const concept = (label, answers, correct = false, options = {}) => ({ label, answers: answers || [label], correct, ...options });

  const paper = {
    id: "higher-2022", title: "Higher Music 2022", level: "Higher", levelCode: "H", year: 2022,
    totalMarks: 40, openingInstructions: ["Total marks — 40", "Attempt ALL questions"], estimatedMinutes: 60,
    sourcePath: "../exampapers/higher/2022/Music H 2022 Paper.pdf",
    markingInstructionsPath: "../exampapers/higher/2022/Music H 2022 Answers.pdf",
    attribution: "Original question paper and audio content © Qualifications Scotland. Interactive adaptation created independently for non-commercial educational use. This resource is not endorsed by Qualifications Scotland.",
    questions: [
      {
        id: "q1", number: "1", marks: 4, topic: "Instrumental music", audio: { clips: [audio(1, [{ label: "1st", time: 39.34 }, { label: "2nd", time: 115.38 }, { label: "3rd", time: 191.52 }])] },
        intro: "This question features instrumental music.",
        subquestions: [{
          id: "q1a", label: "", marks: 4, type: "concept-lines", conceptLayout: "flush", lines: 4, requiredResponses: 4, additionalAnswerPenalty: true,
          leadLines: ["Listen to this excerpt and identify four concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your four answers on the lines below.", boldPhrases: ["four"],
          conceptBank: [concept("Acciaccatura", ["acciaccatura"], true), concept("Concertino"), concept("Passacaglia"), concept("Modal"), concept("Impressionist"), concept("Change of key to relative minor", ["change of key to relative minor", "relative minor"], true), concept("Cluster"), concept("Rondo", ["rondo"], true), concept("Sonata", ["sonata"], true), concept("3 against 2")],
          beforeAnswerLines: ["The music will be played three times with a pause of 10 seconds between playings and a pause of 40 seconds before the next question."],
          afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."],
          answerDisplay: "Acciaccatura, Change of key to relative minor, Rondo and Sonata", definition: "One mark is awarded for each credited concept, in any order.",
        }],
      },
      {
        id: "q2", number: "2", marks: 5, topic: "Musical guide", audio: { clips: [audio(2, [{ label: "1st", time: 69.7 }, { label: "2nd", time: 167.72 }, { label: "3rd", time: 265.9 }])] }, layout: "higher-guide",
        intro: ["In this question you will hear instrumental music.", "A guide to the music is shown below. You are required to complete this guide by inserting music concepts.", "There will now be a pause of 30 seconds to allow you to read through the question.", "The music will be played three times with a pause of 20 seconds between playings. You will then have a further 30 seconds to complete your answer.", "In the first two playings a voice will help guide you through the music.", "There is no voice in the third playing.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introCompactRange: [6, 8],
        subquestions: [
          { id: "q2a", label: "1.", marks: 1, type: "short-text", inlineAnswer: { before: "The introduction ends with a/an", after: "cadence." }, acceptedAnswers: ["perfect"], answerDisplay: "Perfect", definition: "The introduction ends with a perfect cadence." },
          { id: "q2b", label: "2.", marks: 1, type: "short-text", inlineAnswer: { before: "The technique used in the lower strings is", after: "(Italian term)." }, acceptedAnswers: ["pizzicato", "pizz"], alwaysBlockedAnswers: ["plucking"], answerDisplay: "Pizzicato or pizz", definition: "Plucking is not accepted." },
          { id: "q2c", label: "3.", marks: 1, type: "short-text", inlineAnswer: { before: "The tonality changes to", after: "." }, acceptedAnswers: ["major", "relative major"], answerDisplay: "Major or relative major", definition: "The tonality changes to major." },
          { id: "q2d", label: "4.", marks: 1, type: "short-text", inlineAnswer: { before: "The tuned percussion instrument is a/an", after: "." }, acceptedAnswers: ["glockenspiel", "glock"], answerDisplay: "Glockenspiel or glock", definition: "The tuned percussion instrument is a glockenspiel." },
          { id: "q2e", label: "5.", marks: 1, type: "short-text", inlineAnswer: { before: "The final chord outlined in the harp is a/an", after: "." }, acceptedAnswers: ["diminished 7th", "diminished seventh", "dim 7th", "dim 7", "adim7", "a dim7", "a°7"], answerDisplay: "Diminished 7th", definition: "The final chord is a diminished 7th." },
        ],
      },
      {
        id: "q3", number: "3", marks: 4, topic: "Instrumental music", audio: { clips: [audio(3, [{ label: "(a) 1st", time: 16.16 }, { label: "(a) 2nd", time: 56.86 }, { label: "(b)", time: 101.8 }, { label: "(c)", time: 174.98 }, { label: "(d)", time: 226.56 }])] }, intro: "This question features instrumental music.",
        subquestions: [
          { id: "q3a", label: "(a)", marks: 1, type: "radio", promptLines: ["Listen to this excerpt and tick one box to describe what you hear.", "The music will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], options: [option("9/8", "9/8"), option("Interrupted cadence"), option("Irregular time signatures"), option("Tierce de Picardie")], answer: "Irregular time signatures", answerDisplay: "Irregular time signatures", definition: "The excerpt uses irregular time signatures." },
          { id: "q3b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a different excerpt and identify the final chord.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], acceptedAnswers: ["added 6th", "added sixth", "g6", "major 6th", "major sixth"], answerDisplay: "Added 6th, G6 or major 6th", definition: "The final chord is an added 6th." },
          { id: "q3c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and identify the style.", acceptedAnswers: ["jazz funk", "jazz-funk"], answerDisplay: "Jazz funk", definition: "The style is jazz funk." },
          { id: "q3d", label: "(d)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a new excerpt and identify the style.", acceptedAnswers: ["musique concrete", "musique concrète"], answerDisplay: "Musique concrète", definition: "The style is musique concrète." },
        ],
      },
      {
        id: "q4", number: "4", marks: 6, topic: "Music literacy", audio: { clips: [audio(4, [{ label: "Guide", time: 12.92 }, { label: "2nd", time: 209.88 }, { label: "3rd", time: 300.34 }, { label: "4th", time: 386.94 }])] },
        intro: ["This question is based on an arrangement of a song.", "Listen to the excerpt and follow the guide to the music below.", "Here is the music for the first time.", "You now have 2 minutes to read the question.", "All answers must be written in the boxes below."], introBoldPhrases: ["All answers must be written in the boxes below."],
        outro: ["During the next three playings complete your answers (a) to (f).", "The music will be played three more times with a pause of 30 seconds between playings and a pause of 2 minutes before the next question starts.", "Here is the music for the second time.", "Here is the music for the third time.", "Here is the music for the fourth time."], outroBoldPhrases: ["three"], outroCompactRange: [2, 4], outroPosition: "before-score",
        score: { key: "F major", timeSignature: "12/8", bars: 13, sharedNotation: "higher-2022-q4" }, scorePosition: "before",
        subquestions: [
          { id: "q4a", label: "(a)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "time-signature", inlineNotationControls: true, prompt: "Insert the time signature at the appropriate place in the music.", options: [option("2/4", "2/4"), option("3/4", "3/4"), option("4/4", "4/4"), option("6/8", "6/8"), option("9/8", "9/8"), option("12/8", "12/8")], answer: "12/8", answerDisplay: "12/8", definition: "The complete time signature must be inserted using the musical symbol." },
          { id: "q4b", label: "(b)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "At the start of bar 4, insert a note an interval of a 5th higher than the previous note. The rhythm is given above the stave.", options: [], noteSlots: 1, answer: "G5", answerDisplay: "G5 dotted crotchet", definition: "The pitch and rhythm must be correct." },
          { id: "q4c", label: "(c)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Name the chords played in the box in bars 6 and 7. You may use letter names or numbers. The chord at the start of bar 6 is given.", answerReference: { heading: "Choose from the following", rows: [["F", "Chord I"], ["B♭", "Chord IV"], ["C", "Chord V"], ["Dm", "Chord VI"]], footer: "Insert your answers in the boxes provided." }, acceptedAnswers: ["c dm", "c, dm", "c7 dm", "c7, dm", "v vi", "v, vi", "v7 vi", "v7, vi", "5 6", "5, 6"], answerDisplay: "C or C7, followed by Dm; V or V7, followed by VI; or 5 followed by 6", definition: "Both chords must be correct." },
          { id: "q4d", label: "(d)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-select", inlineNotationControls: true, prompt: "The key of the music is F major. Draw a circle around the tonic note in bar 8.", options: [], answer: "F5", answerDisplay: "F5, the third note in bar 8", definition: "The selected note must be the tonic, F." },
          { id: "q4e", label: "(e)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Insert the missing notes in bar 11. The rhythm is given above the stave.", options: [], noteSlots: 3, answer: "A4,G4,Bb4", answerDisplay: "A4, G4 and B♭4 dotted crotchets", definition: "The pitch and rhythm of all three notes must be correct." },
          { id: "q4f", label: "(f)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Transpose the notes in the box in bars 12 and 13 one octave lower into the bass clef. Use the given blank stave.", boldPhrases: ["one octave lower"], options: [], noteSlots: 4, answer: "G3,F3,E3,F3", answerDisplay: "G3 dotted crotchet, F3 crotchet, E3 quaver and F3 dotted minim", definition: "The pitch and rhythm of all four notes must be correct." },
        ],
      },
      {
        id: "q5", number: "5", marks: 5, topic: "Vocal music", audio: { clips: [audio(5, [{ label: "(a) 1st", time: 41.72 }, { label: "(a) 2nd", time: 117.94 }, { label: "(b)", time: 231.14 }, { label: "(c)", time: 314.44 }])] }, intro: "This question features vocal music.",
        subquestions: [
          { id: "q5a", label: "(a)", marks: 3, type: "concept-lines", letteredConcept: true, lines: 3, requiredResponses: 3, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify three concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your three answers on the lines below.", boldPhrases: ["three"], conceptBank: [concept("Whole tone scale"), concept("Coloratura"), concept("Diminution"), concept("Lied", ["lied"], true), concept("Triplets", ["triplets"], true), concept("Recitative"), concept("Rubato", ["rubato"], true), concept("Oratorio"), concept("Ritornello")], beforeAnswerLines: ["The music will be played twice with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], answerDisplay: "Lied, Rubato and Triplets", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q5b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a different excerpt.", "Identify the rhythmic device used at the end of the excerpt."], beforeAnswerLines: ["The music will be played twice.", "Here is the music for the first time.", "Here is the music for the second time."], acceptedAnswers: ["augmentation"], answerDisplay: "Augmentation", definition: "The rhythmic device is augmentation." },
          { id: "q5c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a new excerpt and identify the final cadence. The excerpt will be played twice.", promptLines: ["Listen to a new excerpt and identify the final cadence.", "The excerpt will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], acceptedAnswers: ["interrupted cadence", "interrupted"], answerDisplay: "Interrupted cadence", definition: "The excerpt ends with an interrupted cadence." },
        ],
      },
      {
        id: "q6", number: "6", marks: 5, topic: "Comparing music", audio: { clips: [audio(6, [{ label: "E1 1st", time: 117.26 }, { label: "E2 1st", time: 207.32 }, { label: "E1 2nd", time: 298.14 }, { label: "E2 2nd", time: 385.2 }, { label: "E1 3rd", time: 473.1 }, { label: "E2 3rd", time: 559.44 }, { label: "Column C", time: 637.2 }])] },
        intro: ["In this question you compare two excerpts of music.", "You must first identify concepts present in each excerpt and then decide which five concepts are common to both excerpts. Both excerpts will be played three times with a pause of 10 seconds between playings.", "As you listen, tick boxes in Column A and Column B to identify what you hear in Excerpt 1 and Excerpt 2.", "These columns are for rough work only and will not be marked.", "After the music has been played three times you will be given 2 minutes to decide which concepts are common to both excerpts and to tick five boxes in Column C.", "You now have one minute to read through the question.", "Here is Excerpt 1 for the first time. Remember to tick concepts in Column A.", "Here is Excerpt 2 for the first time. Remember to tick concepts in Column B.", "Here is Excerpt 1 for the second time.", "Here is Excerpt 2 for the second time.", "Here is Excerpt 1 for the third time.", "Here is Excerpt 2 for the third time.", "You now have 2 minutes to identify the five concepts common to both excerpts.", "Remember to tick five boxes only in Column C."], introBoldPhrases: ["five", "three", "Column A", "Column B", "Column C", "These columns are for rough work only and will not be marked.", "Remember to tick concepts in Column A.", "Remember to tick concepts in Column B.", "Remember to tick five boxes only in Column C."], introCompactRanges: [[6, 7], [8, 9], [10, 11]], introTotalMarks: 5, introTotalMarksIndex: 13, showPartMarks: false,
        subquestions: [{ id: "q6a", label: "", marks: 5, type: "comparison-grid", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Identify the five concepts common to both excerpts in Column C. Columns A and B are rough work only.", answers: ["Baroque", "Concerto", "Modulation to relative major", "Sequence", "Basso continuo"], columns: [{ id: "a", label: "Column A", sublabel: "Excerpt 1" }, { id: "b", label: "Column B", sublabel: "Excerpt 2" }, { id: "c", label: "Column C", sublabel: "5 concepts common to both" }], groups: [
          { label: "Style", concepts: [concept("Baroque", ["baroque"], true), concept("Classical"), concept("Romantic"), concept("Concerto", ["concerto"], true), concept("Sonata")] },
          { label: "Melody/harmony", concepts: [concept("Melodic minor scale"), concept("Modulation to relative major", ["modulation to relative major", "relative major"], true), concept("Obbligato"), concept("Sequence", ["sequence"], true)] },
          { label: "Rhythm", concepts: [concept("3 beats in a bar"), concept("Cross rhythms"), concept("Triplets")] },
          { label: "Structure/form", concepts: [concept("Basso continuo", ["basso continuo"], true), concept("Ground bass"), concept("Through-composed")] },
        ], answerDisplay: "Baroque; Concerto; Modulation to relative major; Sequence; Basso continuo", definition: "Only Column C is marked. Additional incorrect selections are deducted." }],
      },
      {
        id: "q7", number: "7", marks: 6, topic: "Listening analysis", audio: { clips: [audio(7, [{ label: "1st", time: 47.48 }, { label: "2nd", time: 143.66 }, { label: "3rd", time: 240.68 }])] },
        intro: ["This question is based on an arrangement of a song.", "In this question you should identify the most prominent concepts which are present in the music.", "As you listen, identify at least two concepts from each of the following headings:", "Melody/harmony", "Rhythm", "Timbre", "", "You will hear the music three times and you should make notes as you listen.", "Rough work will not be marked.", "Marks will only be awarded for the final answer.", "After the third playing you will have 3 minutes to write your final answer in the space provided.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introBoldPhrases: ["two", "Melody/harmony", "Rhythm", "Timbre", "three times", "Rough work will not be marked."], introHeadingRowRange: [3, 5], introCompactRange: [11, 13], introTotalMarks: 6, introTotalMarksIndex: 10, showPartMarks: false,
        subquestions: [{ id: "q7a", label: "Final answer", marks: 6, type: "structured-review", autoMark: true, maxMarksPerHeading: 2, minHeadingsForFullMarks: 3, roughWork: true, finalAnswerField: true, finalAnswerLines: 10, endOfPaper: false, requiredResponses: 6, prompt: "Final answer", headings: [
          { id: "melody", label: "Melody/harmony", concepts: [{ label: "Cluster / discord", answers: ["cluster", "discord"] }, { label: "Countermelody", answers: ["countermelody", "counter melody"] }, { label: "Minor tonality", answers: ["minor", "minor tonality"] }, { label: "Perfect cadence", answers: ["perfect cadence"] }, { label: "Sequence", answers: ["sequence"] }, { label: "Syllabic", answers: ["syllabic"] }] },
          { id: "rhythm", label: "Rhythm", concepts: [{ label: "Simple time / 2 or 4 beats in a bar", answers: ["simple time", "2 beats in a bar", "4 beats in a bar", "2/4", "4/4"] }, { label: "Anacrusis", answers: ["anacrusis", "upbeat"] }, { label: "Dotted rhythms", answers: ["dotted rhythm", "dotted rhythms"] }, { label: "Irregular time signatures / time changes / pauses", answers: ["irregular time signatures", "irregular time signature", "time changes", "pauses"] }, { label: "Rallentando / ritardando / rubato", answers: ["rallentando", "rall", "ritardando", "rit", "rubato"] }, { label: "Syncopation / cross rhythms / 3 against 2", answers: ["syncopation", "cross rhythms", "3 against 2"] }] },
          { id: "timbre", label: "Timbre", concepts: [{ label: "Arco", answers: ["arco"] }, { label: "Cello / string quartet / violins / viola", answers: ["cello", "cellos", "string quartet", "violins", "viola"], blockedAnswers: ["strings", "violin"] }, { label: "Cymbals / triangle / hi-hat / rolls / shakers / maracas", answers: ["cymbals", "triangle", "hi-hat", "hi hat", "rolls", "shakers", "maracas"] }, { label: "Harmonics", answers: ["harmonics", "harmonic"] }, { label: "Mezzo soprano / soprano / alto", answers: ["mezzo soprano", "mezzo-soprano", "soprano", "alto"] }, { label: "Pizzicato", answers: ["pizzicato", "pizz"] }, { label: "Reverb", answers: ["reverb", "reverberation"] }] },
        ], answerDisplay: "Any six valid concepts, with no more than two credited from each heading", additionalGuidance: ["Concepts are credited even when written under a different heading."] }],
      },
      {
        id: "q8", number: "8", marks: 5, topic: "Song features", audio: { clips: [audio(8, [{ label: "1st", time: 93.5 }, { label: "2nd", time: 185.42 }, { label: "3rd", time: 272.12 }])] },
        intro: ["This question is based on a song.", "Below is a list of features which occur in the music.", "You now have one minute to read through the question.", "The song lyrics are shown in the table below. Insert each feature once in the column on the right at the point where it occurs.", "You only need to insert the underlined words."], showPartMarks: false,
        subquestions: [{ id: "q8a", label: "", marks: 5, type: "lyric-placement", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Insert the five underlined words at the point where they occur. Insert each word once only.", playbackLines: ["The music will now be played three times with a pause of 20 seconds between playings and a pause of 30 seconds at the end.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], features: [{ before: "first example of ", word: "trill", after: "" }, { before: "", word: "perfect", after: " cadence" }, { before: "first example of ", word: "glissando", after: "" }, { before: "ascending major ", word: "scale", after: " in the accompaniment" }, { before: "start of ", word: "walking bass", after: "" }], lyricLines: [
            "I look at you and suddenly",
            "Something in your eyes I see",
            "Soon begins bewitching me.",
            "It’s that old devil moon",
            "That you stole from the skies",
            "It’s that old devil moon in your eyes.",
            "You and your glance",
            "Make this romance",
            "Too hot to handle.",
            "Stars in the night",
            "Blazing their light",
            "Can’t hold a candle",
            "To your razzle dazzle."
          ], concepts: [{ id: "glissando", label: "Glissando", answers: ["glissando"], lines: [1, 2] }, { id: "perfect", label: "Perfect", answers: ["perfect", "perfect cadence"], lines: [3, 6] }, { id: "walking-bass", label: "Walking bass", answers: ["walking bass"], lines: [4] }, { id: "trill", label: "Trill", answers: ["trill"], lines: [7, 8] }, { id: "scale", label: "Scale", answers: ["scale", "major scale", "ascending major scale"], lines: [12] }], answerDisplay: "Glissando—line 1 or 2; Perfect—line 3 or 6; Walking bass—line 4; Trill—line 7 or 8; Scale—line 12", definition: "Each feature earns one mark when placed on an accepted lyric line." }],
      },
    ],
  };

  root.InteractiveExamPapers = root.InteractiveExamPapers || {};
  root.InteractiveExamPapers[paper.id] = paper;
  if (typeof module !== "undefined" && module.exports) module.exports = paper;
})(typeof window !== "undefined" ? window : globalThis);
