(function (root) {
  "use strict";
  const audio = (question, markers = []) => { const track = String(question + 1).padStart(2, "0"); return { file: `../exampapers/higher/2023/Music H 2023 - Track ${track}-1.mp3`, label: "Question audio", maxPlaysExam: 1, markers }; };
  const option = (value, label = value) => ({ value, label });
  const concept = (label, answers, correct = false, options = {}) => ({ label, answers: answers || [label], correct, ...options });

  const paper = {
    id: "higher-2023", title: "Higher Music 2023", level: "Higher", levelCode: "H", year: 2023,
    totalMarks: 40, openingInstructions: ["Total marks — 40", "Attempt ALL questions"], estimatedMinutes: 60,
    sourcePath: "../exampapers/higher/2023/NH_Music_QP_2023.pdf", markingInstructionsPath: "../exampapers/higher/2023/mi_NH_Music_mi_2023.pdf",
    attribution: "Original question paper and audio content © Qualifications Scotland. Interactive adaptation created independently for non-commercial educational use. This resource is not endorsed by Qualifications Scotland.",
    questions: [
      {
        id: "q1", number: "1", marks: 5, topic: "Instrumental music", audio: { clips: [audio(1, [{ label: "(a) 1st", time: 42.5 }, { label: "(a) 2nd", time: 116.68 }, { label: "(a) 3rd", time: 190.46 }, { label: "(b)", time: 294.22 }])] }, intro: "This question features instrumental music.",
        subquestions: [
          { id: "q1a", label: "(a)", marks: 4, type: "concept-lines", letteredConcept: true, lines: 4, requiredResponses: 4, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify four concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your four answers on the lines below.", boldPhrases: ["four"], conceptBank: [concept("Pedal", ["pedal", "pedal note"], true), concept("Tremolando"), concept("Sonata"), concept("Mordent"), concept("Ripieno"), concept("Descant"), concept("Diminished 7th", ["diminished 7th", "diminished seventh", "dim 7th"], true), concept("String quartet", ["string quartet"], true), concept("Rubato"), concept("Acciaccatura", ["acciaccatura"], true)], beforeAnswerLines: ["The music will be played three times with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], answerDisplay: "Acciaccatura, Diminished 7th, Pedal and String quartet", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q1b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to a different excerpt.", "Write the concept which describes the structure/form of the music."], acceptedAnswers: ["passacaglia"], answerDisplay: "Passacaglia", definition: "The structure/form is passacaglia." },
        ],
      },
      {
        id: "q2", number: "2", marks: 5, topic: "Musical guide", audio: { clips: [audio(2, [{ label: "1st", time: 70.66 }, { label: "2nd", time: 185.36 }, { label: "3rd", time: 300.24 }])] }, layout: "higher-guide",
        intro: ["In this question you will hear orchestral music.", "A guide to the music is shown below. You are required to complete this guide by inserting music concepts.", "There will now be a pause of 30 seconds to allow you to read through the question.", "The music will be played three times with a pause of 20 seconds between playings. You will then have a further 30 seconds to complete your answer.", "In the first two playings a voice will help guide you through the music.", "There is no voice in the third playing.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introCompactRange: [6, 8],
        subquestions: [
          { id: "q2a", label: "1.", marks: 1, type: "short-text", inlineAnswer: { before: "The texture of the opening is", after: "." }, acceptedAnswers: ["homophonic"], answerDisplay: "Homophonic", definition: "The opening texture is homophonic." },
          { id: "q2b", label: "2.", marks: 1, type: "short-text", inlineAnswer: { before: "The cadence is", after: "." }, acceptedAnswers: ["interrupted", "interrupted cadence"], answerDisplay: "Interrupted", definition: "The cadence is interrupted." },
          { id: "q2c", label: "3.", marks: 1, type: "short-text", inlineAnswer: { before: "The instrumental technique in the accompaniment is", after: "(Italian term)." }, acceptedAnswers: ["pizzicato", "pizz"], alwaysBlockedAnswers: ["plucking"], answerDisplay: "Pizzicato or pizz", definition: "Plucking is not accepted." },
          { id: "q2d", label: "4.", marks: 1, type: "short-text", inlineAnswer: { before: "The instrument playing the descending chromatic scale is a/an", after: "." }, acceptedAnswers: ["french horn", "horn"], answerDisplay: "French horn or horn", definition: "The instrument is a French horn." },
          { id: "q2e", label: "5.", marks: 1, type: "short-text", inlineAnswer: { before: "The final chord is a/an", after: "." }, acceptedAnswers: ["dominant 7th", "dominant seventh", "bb7", "b flat 7", "b♭7"], answerDisplay: "Dominant 7th or B♭7", definition: "The final chord is a dominant 7th." },
        ],
      },
      {
        id: "q3", number: "3", marks: 3, topic: "Contrasting vocal styles", audio: { clips: [audio(3, [{ label: "(a) 1st", time: 18.58 }, { label: "(a) 2nd", time: 33.42 }, { label: "(b)", time: 61.2 }, { label: "(c)", time: 117.9 }])] }, intro: "This question features contrasting styles of vocal music.",
        subquestions: [
          { id: "q3a", label: "(a)", marks: 1, type: "radio", promptLines: ["Listen to this excerpt and tick one box to describe what you hear.", "The music will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], options: ["Augmentation", "Diminution", "Time changes", "3 against 2"].map(value => option(value)), answer: "Augmentation", answerDisplay: "Augmentation", definition: "The excerpt uses augmentation." },
          { id: "q3b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and identify the style.", acceptedAnswers: ["plainchant", "plainsong"], answerDisplay: "Plainchant or plainsong", definition: "The vocal style is plainchant." },
          { id: "q3c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to another piece of music and identify the type of work.", "The music will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], acceptedAnswers: ["mass"], answerDisplay: "Mass", definition: "The work is a mass." },
        ],
      },
      {
        id: "q4", number: "4", marks: 6, topic: "Music literacy", audio: { clips: [audio(4, [{ label: "Guide", time: 12.22 }, { label: "2nd", time: 201.1 }, { label: "3rd", time: 273.28 }, { label: "4th", time: 345.92 }])] },
        intro: ["This question is based on a popular song.", "Listen to the excerpt and follow the guide to the music below.", "Here is the music for the first time.", "You now have 2 minutes to read the question.", "All answers must be written in the boxes below."], introBoldPhrases: ["All answers must be written in the boxes below."],
        outro: ["During the next three playings complete your answers (a) to (f).", "The music will be played three more times with a pause of 30 seconds between playings and a pause of 2 minutes before the next question starts.", "Here is the music for the second time.", "Here is the music for the third time.", "Here is the music for the fourth time."], outroBoldPhrases: ["three"], outroCompactRange: [2, 4], outroPosition: "before-score",
        score: { key: "F major", timeSignature: "4/4", bars: 16, sharedNotation: "higher-2023-q4" }, scorePosition: "before",
        subquestions: [
          { id: "q4a", label: "(a)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "At the start of bar 2, insert a note a 4th higher than the previous note. The rhythm is given above the stave.", options: [], noteSlots: 1, answer: "D5", answerDisplay: "D5 quaver", definition: "The pitch and rhythm must be correct." },
          { id: "q4b", label: "(b)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Transpose the boxed notes in bar 4 one octave lower into the bass clef. Use the given blank stave.", options: [], noteSlots: 5, answer: "G3,G3,F3,D3,D3", answerDisplay: "G3, G3, F3 and D3 quavers followed by D3 crotchet", definition: "The pitch and rhythm of all five notes must be correct; the tie may be above or below." },
          { id: "q4c", label: "(c)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "note-entry", inlineNotationControls: true, prompt: "Insert the missing notes in bar 7. The rhythm is given above the stave.", options: [], noteSlots: 3, answer: "A4,G4,F4", answerDisplay: "A4, G4 and F4 quavers", definition: "The pitch and rhythm of all three notes must be correct." },
          { id: "q4d", label: "(d)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "rhythm-entry", inlineNotationControls: true, prompt: "Correct the rhythm in bar 9 to match what you hear.", options: [option("dottedCrotchet", "Dot"), option("quaver", "Quaver tail")], noteSlots: 2, answer: "quaver,dottedCrotchet", answerDisplay: "Quaver followed by dotted crotchet", definition: "The tail and augmentation dot must be shown." },
          { id: "q4e", label: "(e)", marks: 1, type: "notation-choice", sharedScore: true, notationTool: "rhythm-entry", inlineNotationControls: true, prompt: "Insert the missing rest(s) in bar 12.", options: [option("crotchetRest", "Crotchet rest"), option("quaverRest", "Quaver rest"), option("dottedCrotchetRest", "Dotted crotchet rest")], noteSlots: 3, answer: "crotchetRest,quaverRest", acceptedAnswers: ["crotchetRest,quaverRest", "quaverRest,quaverRest,quaverRest", "dottedCrotchetRest"], answerDisplay: "Crotchet rest plus quaver rest; three quaver rests; or one dotted crotchet rest", definition: "A quaver followed by a crotchet is not accepted." },
          { id: "q4f", label: "(f)", marks: 1, type: "short-text", answerInScore: true, capitaliseAnswer: true, prompt: "Name the chords that you hear in bars 14 and 15. You may use letter names or numbers. The first chord is given.", answerReference: { heading: "Choose from the following", rows: [["F", "Chord I"], ["B♭", "Chord IV"], ["C", "Chord V"], ["Dm", "Chord VI"]], footer: "Insert your answers in the boxes provided." }, acceptedAnswers: ["bb c", "bb, c", "b flat c", "b flat, c", "iv v", "iv, v", "4 5", "4, 5"], answerDisplay: "B♭ and C; IV and V; or 4 and 5", definition: "Both chords must be correct." },
        ],
      },
      {
        id: "q5", number: "5", marks: 5, topic: "Vocal music", audio: { clips: [audio(5, [{ label: "(a) 1st", time: 44.36 }, { label: "(a) 2nd", time: 108.06 }, { label: "(b)", time: 201.14 }, { label: "(c)", time: 245.4 }])] }, intro: "This question features vocal music.",
        subquestions: [
          { id: "q5a", label: "(a)", marks: 3, type: "concept-lines", letteredConcept: true, lines: 3, requiredResponses: 3, additionalAnswerPenalty: true, leadLines: ["Listen to this excerpt and identify three concepts in the music from those listed below.", "Read through the concepts before hearing the music."], prompt: "Give your three answers on the lines below.", boldPhrases: ["three"], conceptBank: [concept("Recitative"), concept("Melismatic", ["melismatic"], true), concept("Plagal cadence"), concept("Concertino"), concept("Basso continuo", ["basso continuo"], true), concept("Obbligato", ["obbligato"], true), concept("Lied"), concept("Rondo"), concept("Alberti bass")], beforeAnswerLines: ["The music will be played twice with a pause of 10 seconds between playings and a pause of 40 seconds before part (b)."], afterAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], answerDisplay: "Basso continuo, Melismatic and Obbligato", definition: "One mark is awarded for each credited concept, in any order." },
          { id: "q5b", label: "(b)", marks: 1, type: "short-text", capitaliseAnswer: true, prompt: "Listen to a different excerpt and identify the vocal timbre.", acceptedAnswers: ["coloratura"], answerDisplay: "Coloratura", definition: "The vocal timbre is coloratura." },
          { id: "q5c", label: "(c)", marks: 1, type: "short-text", capitaliseAnswer: true, promptLines: ["Listen to another piece of music.", "Write the concept which describes the harmonic feature at the end of the excerpt.", "The music will be played twice."], beforeAnswerLines: ["Here is the music for the first time.", "Here is the music for the second time."], acceptedAnswers: ["tierce de picardie", "tierce de picardy", "picardy third", "picardie third"], answerDisplay: "Tierce de Picardie", definition: "The harmonic feature is a Tierce de Picardie." },
        ],
      },
      {
        id: "q6", number: "6", marks: 6, topic: "Listening analysis", audio: { clips: [audio(6, [{ label: "1st", time: 50.46 }, { label: "2nd", time: 137.9 }, { label: "3rd", time: 224.8 }])] },
        intro: ["This question is based on instrumental music.", "In this question you should identify the most prominent concepts which are present in the music.", "As you listen, identify at least two concepts from each of the following headings:", "Melody/harmony", "Rhythm", "Style/texture", "", "You will hear the music three times and you should make notes as you listen.", "Rough work will not be marked.", "Marks will only be awarded for the final answer.", "After the third playing you will have 3 minutes to write your final answer in the space provided.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], introBoldPhrases: ["two", "Melody/harmony", "Rhythm", "Style/texture", "three times", "Rough work will not be marked."], introHeadingRowRange: [3, 5], introCompactRange: [11, 13], introTotalMarks: 6, introTotalMarksIndex: 10, showPartMarks: false,
        subquestions: [{ id: "q6a", label: "Final answer", marks: 6, type: "structured-review", autoMark: true, maxMarksPerHeading: 2, minHeadingsForFullMarks: 3, roughWork: true, finalAnswerField: true, finalAnswerLines: 10, endOfPaper: false, requiredResponses: 6, prompt: "Final answer", headings: [
          { id: "melody", label: "Melody/harmony", concepts: [{ label: "Acciaccatura", answers: ["acciaccatura"] }, { label: "Broken chord", answers: ["broken chord", "broken chords"] }, { label: "Chromatic", answers: ["chromatic"] }, { label: "Dominant 7th", answers: ["dominant 7th", "dominant seventh"] }, { label: "Major", answers: ["major", "major tonality"] }, { label: "Melodic minor / minor scale", answers: ["melodic minor", "melodic minor scale", "minor scale"], alwaysBlockedAnswers: ["harmonic minor", "harmonic minor scale"] }, { label: "Minor / relative minor", answers: ["minor", "minor tonality", "relative minor"], alwaysBlockedAnswers: ["harmonic minor", "harmonic minor scale"] }, { label: "Modulation / change of key", answers: ["modulation", "change of key"] }, { label: "Perfect cadence", answers: ["perfect cadence"] }] },
          { id: "rhythm", label: "Rhythm", concepts: [{ label: "Simple time / 2/4 / 4/4", answers: ["simple time", "2/4", "4/4"], blockedAnswers: ["2 beats in the bar", "4 beats in the bar"] }, { label: "3 against 2", answers: ["3 against 2", "three against two"] }, { label: "Anacrusis", answers: ["anacrusis", "upbeat"] }, { label: "Rallentando / ritardando", answers: ["rallentando", "rall", "ritardando", "rit"] }, { label: "Rubato", answers: ["rubato"] }, { label: "Triplets", answers: ["triplet", "triplets"] }] },
          { id: "style", label: "Style/texture", concepts: [{ label: "Baroque", answers: ["baroque"] }, { label: "Chamber music", answers: ["chamber music"] }, { label: "Homophonic", answers: ["homophonic"] }, { label: "Sonata", answers: ["sonata"], alwaysBlockedAnswers: ["sonata form"] }] },
        ], answerDisplay: "Any six valid concepts, with no more than two credited from each heading", additionalGuidance: ["Concepts are credited even when written under a different heading."] }],
      },
      {
        id: "q7", number: "7", marks: 5, topic: "Comparing music", audio: { clips: [audio(7, [{ label: "E1 1st", time: 120.48 }, { label: "E2 1st", time: 208.98 }, { label: "E1 2nd", time: 300.72 }, { label: "E2 2nd", time: 385.46 }, { label: "E1 3rd", time: 475.2 }, { label: "E2 3rd", time: 558.04 }, { label: "Column C", time: 636.82 }])] },
        intro: ["In this question you are to compare two excerpts of music.", "You must first identify concepts present in each excerpt and then decide which five concepts are common to both excerpts. Both excerpts will be played three times with a pause of 10 seconds between playings.", "As you listen, tick boxes in Column A and Column B to identify what you hear in Excerpt 1 and Excerpt 2.", "These columns are for rough work only and will not be marked.", "After the music has been played three times you will be given 2 minutes to decide which concepts are common to both excerpts and to tick five boxes in Column C.", "You now have one minute to read through the question.", "Here is Excerpt 1 for the first time. Remember to tick concepts in Column A.", "Here is Excerpt 2 for the first time. Remember to tick concepts in Column B.", "Here is Excerpt 1 for the second time.", "Here is Excerpt 2 for the second time.", "Here is Excerpt 1 for the third time.", "Here is Excerpt 2 for the third time.", "You now have 2 minutes to identify the five concepts common to both excerpts.", "Remember to tick five boxes only in Column C."], introBoldPhrases: ["five", "three", "Column A", "Column B", "Column C", "These columns are for rough work only and will not be marked.", "Remember to tick concepts in Column A.", "Remember to tick concepts in Column B.", "Remember to tick five boxes only in Column C."], introCompactRanges: [[6, 7], [8, 9], [10, 11]], introTotalMarks: 5, introTotalMarksIndex: 13, showPartMarks: false,
        subquestions: [{ id: "q7a", label: "", marks: 5, type: "comparison-grid", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Identify the five concepts common to both excerpts in Column C. Columns A and B are rough work only.", answers: ["Classical", "Concerto", "Trill", "Anacrusis", "Triplet"], columns: [{ id: "a", label: "Column A", sublabel: "Excerpt 1" }, { id: "b", label: "Column B", sublabel: "Excerpt 2" }, { id: "c", label: "Column C", sublabel: "5 concepts common to both" }], groups: [
          { label: "Styles", concepts: [concept("Classical", ["classical"], true), concept("Romantic"), concept("Concerto", ["concerto"], true), concept("Symphony")] },
          { label: "Melody/harmony", concepts: [concept("Mode"), concept("Mordent"), concept("Trill", ["trill"], true)] },
          { label: "Rhythm/tempo", concepts: [concept("Accelerando"), concept("Anacrusis", ["anacrusis"], true), concept("Triplet", ["triplet", "triplets"], true)] },
          { label: "Texture/structure/form", concepts: [concept("Concerto grosso"), concept("Through-composed"), concept("Unison/octaves"), concept("Ritornello")] },
        ], answerDisplay: "Classical; Concerto; Trill; Anacrusis; Triplet", definition: "Only Column C is marked. Additional incorrect selections are deducted." }],
      },
      {
        id: "q8", number: "8", marks: 5, topic: "Song features", audio: { clips: [audio(8, [{ label: "1st", time: 102.62 }, { label: "2nd", time: 171.12 }, { label: "3rd", time: 240.1 }])] },
        intro: ["This question is based on a song from a musical.", "Below is a list of features which occur in the music.", "You now have one minute to read through the question.", "The song lyrics are shown in the table below. Insert each feature once in the column on the right at the point where it occurs.", "You only need to insert the underlined words."], showPartMarks: false,
        subquestions: [{ id: "q8a", label: "", marks: 5, type: "lyric-placement", requiredResponses: 5, additionalAnswerPenalty: true, hidePrompt: true, prompt: "Insert the five underlined words at the point where they occur. Insert each word once only.", playbackLines: ["The music will now be played three times with a pause of 20 seconds between playings and a pause of 30 seconds at the end.", "Here is the music for the first time.", "Here is the music for the second time.", "Here is the music for the third time."], features: [{ before: "", word: "perfect", after: " cadence" }, { before: "xylophone ", word: "glissando", after: "" }, { before: "start of ", word: "tremolando", after: "" }, { before: "start of ", word: "violin", after: " countermelody" }, { before: "first example of ", word: "con sordino", after: " trumpets" }], lyricLines: [
            "Give ‘em the old razzle dazzle.",
            "Razzle dazzle ‘em.",
            "Give ‘em a show that’s",
            "So splendiferous,",
            "Row after row will",
            "grow vociferous",
            "Give ‘em the old",
            "Flim flam flummox.",
            "Fool and fracture ‘em.",
            "How can they hear",
            "The truth above the roar.",
            "Throw ‘em a fake and a finagle.",
            "They’ll never know",
            "You’re just the bagel.",
            "Razzle dazzle ‘em",
            "And they’ll beg you for more."
          ], concepts: [{ id: "con-sordino", label: "Con sordino", answers: ["con sordino", "con sordino trumpets"], lines: [1] }, { id: "violin", label: "Violin", answers: ["violin", "violin countermelody"], lines: [2, 3] }, { id: "tremolando", label: "Tremolando", answers: ["tremolando", "tremolo"], lines: [11] }, { id: "glissando", label: "Glissando", answers: ["glissando", "xylophone glissando"], lines: [13] }, { id: "perfect", label: "Perfect", answers: ["perfect", "perfect cadence"], lines: [16] }], answerDisplay: "Con sordino—line 1; Violin—line 2 or 3; Tremolando—line 11; Glissando—line 13; Perfect—line 16", definition: "Each feature earns one mark when placed on an accepted lyric line." }],
      },
    ],
  };
  root.InteractiveExamPapers = root.InteractiveExamPapers || {};
  root.InteractiveExamPapers[paper.id] = paper;
  if (typeof module !== "undefined" && module.exports) module.exports = paper;
})(typeof window !== "undefined" ? window : globalThis);
